= Integrate with an external Prometheus and Grafana instance
:navtitle: Integrate external Prometheus and Grafana

{product} exposes some of the {pulsar-reg} metrics through Prometheus endpoints.
The Prometheus configuration information to scrape {product} metrics into an external Prometheus server is found in the {astra-ui}.

This page explains how to set up a Prometheus server in a Kubernetes cluster and configure it to scrape {product} metrics.

== Prerequisites

* An active {product-short} account
* A Kubernetes cluster

== Configure and deploy Prometheus

This example uses the https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack[Prometheus Community Kubernetes Helm Charts] to set up a Prometheus server and a Grafana server in a Kubernetes cluster.

. Download the {product} Prometheus configuration from the {astra-ui}.
For more information, see xref:operations:astream-scrape-metrics.adoc[Scrape metrics from {product}].

. Use the downloaded file to create a `config.yml`.
+
This example uses a job named `astra-pulsar-metrics-demo`.
The values in your `config.yml` depend on your tenant configuration.
+
.config.yml
[source,yaml,subs="+quotes"]
----
  - job_name: "astra-pulsar-metrics-demo"

    scheme: 'https'
    metrics_path: '/pulsarmetrics/**TENANT_NAME**'
    authorization:
      credentials: '**PULSAR_JWT_TOKEN**'

    static_configs:
      - targets: [https://prometheus-**PROVIDER**-**REGION**.streaming.datastax.com/pulsarmetrics/**TENANT_NAME**]
----
+
[IMPORTANT]
====
Do _not_ add other Prometheus configurations, like `scrape_interval` or `evaluation_interval` yet.
These are added later when configuring the Helm chart.
====

. Create a Kubernetes secret with the above configuration file, and then apply it:
+
[source,bash,subs="+quotes"]
----
kubectl create secret generic **SECRET_NAME** \
  --from-file=config.yml \
  --dry-run=client -oyaml > k8s-additional-scrape-config-demo.yaml
kubectl apply -f k8s-additional-scrape-config-demo.yaml
----
+
You can change the name of the YAML output file, if desired.

. Create a customized values file (`custom-values.yml`) for the Prometheus Community Kubernetes Helm chart.
In the 'additionalScrapeConfigsSecret' section, make sure the `name` and `key` match the name if your Kubernetes secret and config file name, such as `astra-secret` and `config.yml`.
+
.custom-values.yml
[source,yaml,subs="+quotes"]
----
prometheus:
   prometheusSpec:
      scrapeInterval: 60s
      evaluationInterval: 15s
      additionalScrapeConfigsSecret:
         enabled: true
         name: *SECRET_NAME*
         key: *CONFIG_YAML*
----

. Deploy the Helm chart:
+
[source,shell]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm upgrade --install kubeprom -f custom-values.yaml prometheus-community/kube-prometheus-stack
----

. For macOS users who run Docker Desktop as the underlying Kubernetes cluster, run the following commands to ensure the deployment is successful.
If you don't run this command, you might encounter a problem when initializing the Prometheus node exporter daemon set.
+
[source,shell]
----
# Patch Prometheus node exporter daemon set
kubectl patch ds kubeprom-prometheus-node-exporter --type "json" -p '[{"op": "remove", "path" : "/spec/template/spec/containers/0/volumeMounts/2/mountPropagation"}]'

# Confirm Prometheus node exporter daemonset is running properly
kubectl rollout status daemonset \
  kubeprom-prometheus-node-exporter \
  --timeout 60s
----

. To confirm that {product} metrics are integrated with your external Prometheus server, go to your external Prometheus server UI.
Make sure the additional scrape job is in `UP` status.
If not, review the configuration instructions and YAML examples to ensure your configuration is correct.
+
If the additional scrape job returns a `401 Unauthorized` error, make sure your {pulsar-short} JWT isn't expired.
For more information, see xref:astream-token-gen.adoc[].

== See also

* xref:monitoring/index.adoc[]
* xref:monitoring/metrics.adoc[]
* xref:monitoring/new-relic.adoc[]

