= New Relic Integration

While there are multiple ways to https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic[send external Prometheus data to New Relic], one the https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/#remote-write[Prometheus remote write integration] option is relevant to {product}.

== Prerequisites

* Review xref:monitoring/index.adoc[].
* https://docs.newrelic.com/[Set up a New Relic account.]
* Save your new relic license key locally.

== Prepare the extra Prometheus server

* xref:monitoring/integration.adoc[Install an extra Prometheus server] to act as a bridge to forward scraped {product} metrics to New Relic.

This is required because {product} is a managed service, and you can't modify the {product} Prometheus server as required by the New Relic Prometheus write integration.

== Configure New Relic

Configure the `remoteWrite` integration on your local Prometheus server.
For more information, see https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/[Set up your Prometheus remote write integration].

This example uses a local Prometheus server installed in a local Docker Desktop Kubernetes cluster.
Your `remoteWrite` configuration depends on your Prometheus server setup.

. In your New Relic account, click *Add Data*.

. Under *Open source monitoring*, select *Prometheus Remote Write Integration*.

. Enter the name of your local Prometheus server, such as `prometheus-docker-desktop`, and then click *Generate URL*.
This generates the endpoint URLs required to configure a `remote_write` integration on your local Prometheus server.

. Create a Kubernetes secret with your New Relic license key:
+
[source,shell,subs="+quotes"]
----
kubectl create secret generic nr-license-key --from-literal=value=**LICENSE_KEY**
----

. In your extra Prometheus server's `custom-values.yaml` file, add the `remoteWrite` configuration to send local Prometheus metrics to New Relic through `remote_write`:
+
.custom-values.yaml
[source,yaml,subs="+quotes"]
----
prometheus:
   prometheusSpec:
      scrapeInterval: 60s
      evaluationInterval: 15s
      additionalScrapeConfigsSecret:
         enabled: true
         name: *SECRET_NAME*
         key: *CONFIG_YAML*

      remoteWrite:
        - url: https://metric-api.newrelic.com/prometheus/v1/write?prometheus_server=**CLUSTER_NAME**
          authorization:
            credentials:
              key: value
              name: nr-license-key
----

. Restart your local Prometheus server.

. In your New Relic account, go to the *Remote Write Dashboard* to confirm that {product} metrics are visible in New Relic.

== See also

* For a list of exposed endpoints for {product} metrics, see xref:monitoring/metrics.adoc[].
* To scrape {product} metrics in Kubernetes with an external Prometheus server, see xref:monitoring/integration.adoc[].
* To scrape {product} metrics into New Relic, see xref:monitoring/new-relic.adoc[].