= Topic dashboard

The https://github.com/datastax/astra-streaming-examples/blob/master/grafana-dashboards/as-topic.json[topic dashboard] aggregates metrics at the topic level. In the variable section, you can choose a cluster, tenant, and namespace, and topic.
This dashboard analyzes metrics at the parent topic level, not at the partition level.

== Topic overview

Overview displays the aggregated total metrics values summarized at the topic level.

* Total number of producers
* Total number of consumers
* Total number of subscriptions
* Total message backlog
* Total message replication backlog
* Total message storage size -  after replication
* Total message size offloaded to a tiered storage
* Total hourly incoming message number
* Total hourly incoming message average size

== Messaging

Messaging displays the time series metrics chart summarized at the topic level with an additional level of detail (partitions).

* Total incoming message rate (msg/s) of the topic divided by partitions
* Total outgoing message rate (msg/s) of the topic divided by partitions
* Total incoming message throughput (bytes/s) of the topic divided by partitions
* Total outgoing message throughput (bytes/s) of the topic divided by partitions
* Total message backlog of the topic divided by partitions
* Total unacknowledged messages of the topic divided by partitions

=== Subscription

Subscription displays the time series metrics chart summarized at the subscription level with an additional level of detail (by individual subscriptions).

* Total subscription message backlog divided by individual subscriptions
* Total subscription message backlog with no delay divided by individual subscriptions
* Total subscription unacknowledged messages divided by individual subscriptions
* Total subscription delayed messages divided by individual subscriptions
* Total subscription message dispatch rate (msg/s) divided by individual subscriptions
* Total subscription message throughput rate (byte/s) divided by individual subscriptions
* Total subscription message acknowledgement rate (msg/s) divided by individual subscriptions
* Total subscription message redelivery rate (msg/s) divided by individual subscriptions
* Total subscription message expired rate (msg/s) divided by individual subscriptions
* Total subscription message dropped rate (msg/s) divided by individual subscriptions
* Total subscription messages processed by EntryFilter, divided by individual subscriptions
* Total subscription messages accepted by EntryFilter, divided by individual subscriptions
* Total subscription messages rejected by EntryFilter, divided by individual subscriptions
* Total subscription messages rescheduled by EntryFilter, divided by individual subscriptions

== Georeplication

Georeplication displays the time series metrics chart summarized at the topic level with an additional level of detail (remote clusters).

* Incoming replication rate (msg/s) to the topic divided by remote clusters
* Outgoing replication rate (msg/s) from the topic divided by remote clusters
* Incoming replication throughput (byte/s) to the topic divided by remote clusters
* Outgoing replication throughput (byte/s) from the topic divided by remote clusters
* Total (outgoing) message replication backlog from the topic divided by remote clusters

== See also

Dashboards are available for scraping metrics at Pulsar's xref:monitoring/overview-dashboard.adoc[tenant], xref:monitoring/namespace-dashboard.adoc[namespace], and xref:monitoring/topic-dashboard.adoc[topic] levels.