= Exclusive subscriptions in {pulsar-reg}
:navtitle: Exclusive
:subscription-comment: // Subscription type is set to Exclusive
:subscription-type: .subscriptionType(SubscriptionType.Exclusive)

_Subscriptions_ in {pulsar-reg} describe which consumers are consuming data from a topic and how they want to consume that data.

An _exclusive subscription_ describes a basic publish-subscribe (pub-sub) pattern where a single consumer subscribes to a single topic and consumes from it.

This page explains how to use {pulsar-short}'s exclusive subscription model to manage your topic consumption.

== Prerequisites

include::ROOT:partial$subscription-prereq.adoc[]

== Prepare example project and producer

include::ROOT:partial$subscription-setup-project.adoc[]


[#example]
== Create consumer with exclusive subscription

To create a {pulsar-short} exclusive subscription, create a `pulsarConsumer` with `{subscription-type}`.

. In `src/main/java/com/datastax/pulsar`, create a `SimplePulsarConsumer.java` file with the following contents:
+
.SimplePulsarConsumer.java
[source,java,subs="+attributes"]
----
include::ROOT:partial$simplepulsarconsumer.java[]
----
+
Alternatively, you can omit the `.subscriptionType` declaration because `Exclusive` is the default subscription type:
+
.SimplePulsarConsumer.java with implied exclusive subscription
[source,java]
----
            pulsarConsumer = pulsarClient.newConsumer(Schema.JSON(DemoBean.class))
                    .topic("persistent://"
                            + conf.getTenantName() + "/"
                            + conf.getNamespace() + "/"
                            + conf.getTopicName())
                    .startMessageIdInclusive()
                    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                    .subscriptionName("SimplePulsarConsumer")
                    // No subscriptionType declaration, defaults to Exclusive
                    .subscribe();
----

== Test exclusive subscription

include::ROOT:partial$subscription-start-consumer.adoc[]

. In a new terminal window, run `SimplePulsarProducer.java` to begin producing messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 93573631 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 16931522 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 68306175 sent
----
+
In the `SimplePulsarConsumer` terminal, the consumer begins consuming the produced messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":93573631,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":16931522,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":68306175,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
----

. In a new terminal window, try to run another instance of `SimplePulsarConsumer.java`.
+
The second consumer cannot subscribe to the topic because the subscription is exclusive:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.Configuration - Configuration has been loaded successfully
...
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - SimplePulsarProducer has been stopped.
Exception in thread "main" java.lang.IllegalStateException: Cannot connect to pulsar
	at com.datastax.pulsar.SimplePulsarConsumer.main(SimplePulsarConsumer.java:53)
Caused by: org.apache.pulsar.client.api.PulsarClientException$ConsumerBusyException: {"errorMsg":"Exclusive consumer is already connected","reqId":2964994443801550457, "remote":"<service_url>", "local":"/192.168.0.95:55777"}
----

== See also

* xref:astream-subscriptions.adoc[]
* xref:astream-subscriptions-shared.adoc[]
* xref:astream-subscriptions-failover.adoc[]
* xref:astream-subscriptions-keyshared.adoc[]
