= {product} FAQs
:navtitle: FAQs
:page-tag: astra-streaming,dev,admin,planner,plan,pulsar

== How do I get started with {product}?

See xref:getting-started:index.adoc[].

== How is {product} priced?

See xref:operations:astream-pricing.adoc[].

== Why is {product} based on Apache Pulsar?

See our https://www.datastax.com/blog/four-reasons-why-apache-pulsar-essential-modern-data-stack[blog post] that explains why we are excited about Apache Pulsar and why we decided it was the best technology to base {product} on.

== What will happen to Kesque?

{product} is based heavily on technology originally created as part of Kesque. With the launch of {product} we will begin the process of shutting down the Kesque service and migrating customers to the new {product} platform.

== Who should use {product}?

{product} has been architected to satisfy the most stringent enterprise requirements around availability, scale, and latency.
{product} was built to handle mission critical use cases for Fortune 100 companies across BFSI, Telecommunications, Technology, Retail, Oil and Gas, and Healthcare.

The pricing model also makes {product} accessible to mid market and small/medium business customers who need event stream processing capabilities to run core parts of their business.

And finally {product} offers a user-friendly interface and free tier to satisfy the needs of individual developers and technologists who want to learn more about Apache Pulsar and data streaming in general.

== What is CDC for {astra_db}?

Change Data Capture (CDC) for {astra_db} uses a Pulsar IO source connector that processes changes from the Cassandra Change Agent via a Pulsar topic.
For more information, see xref:developing:astream-cdc.adoc[].

== What are tenants, namespaces, topics, and sinks?

*Tenants* are an isolated administrative unit for which an authorization scheme can be set and a set of clusters can be defined.
Each tenant can have multiple *namespaces*, a logical container for creating and managing a hierarchy of topics.
A *topic* is a named channel for transmitting messages from producers to consumers.
A *sink* feeds data from {product} to an external system, such as Cassandra or Elastic Search.

== See also

* xref:getting-started:index.adoc[]
* Browse the xref:apis:index.adoc[]
