= Key shared subscriptions in {pulsar-reg}
:navtitle: Key shared
:subscription-comment: // Subscription type is set to Key_Shared
:subscription-type: .subscriptionType(SubscriptionType.Key_Shared)

_Subscriptions_ in {pulsar-reg} describe which consumers are consuming data from a topic and how they want to consume that data.

{pulsar-short}'s xref:astream-subscriptions-shared.adoc[shared subscription] model can increase the message processing rate, but it risks losing message ordering guarantees.
In a round-robin delivery, there's no way for the broker to know which messages are going to which consumer.

_Key shared subscriptions_ allow multiple consumers to subscribe to a topic, and provide additional metadata in the form of _keys_ that link messages to specific consumers.
Keys are generated with hashing that converts arbitrary values like `topic-name` or JSON blobs into fixed integer values, and then the hashed values are assigned to subscribed consumers in one of two ways:

* *Auto hash*: Uses _consistent hashing_ to balance range values across available consumers without requiring manual setup of hash ranges.
* *Sticky hash*: The client manually assigns consumer range values, and then all hashes within a configured range go to one consumer.

This page explains how to use {pulsar-short}'s key shared subscription model to manage your topic consumption.

== Prerequisites

include::ROOT:partial$subscription-prereq.adoc[]

== Prepare example project and producer

include::ROOT:partial$subscription-setup-project.adoc[]

[#example]
== Create consumer with key shared subscription

To create a {pulsar-short} key shared subscription, create a `pulsarConsumer` with `{subscription-type}` and a `keySharedPolicy` configuration.
The `keySharedPolicy` defines how hashed values are assigned to subscribed consumers.

For the simplest configuration, use the `<<use-autosplithashrange,autoSplitHashRange>>` policy.

If you need to set fixed hash ranges, use the `<<use-stickyhashrange,stickyHashRange>>` policy.

[#use-autosplithashrange]
=== Use autoSplitHashRange

To automatically assign hash ranges to consumers, use the `autoSplitHashRange` policy.
Running multiple consumers with `autoSplitHashRange` balances the messaging load across all available consumers, like a xref:astream-subscriptions-shared.adoc[shared subscription].

. In `src/main/java/com/datastax/pulsar`, create a `SimplePulsarConsumer.java` file with the following contents:
+
.SimplePulsarConsumer.java
[source,java,subs="+attributes"]
----
include::ROOT:partial$simplepulsarconsumer.java[]
----

. In `pulsarConsumer`, add `.keySharedPolicy(KeySharedPolicy.autoSplitHashRange())`:
+
.SimplePulsarConsumer.java with autoSplitHashRange
[source,java,subs="+attributes"]
----
...

pulsarConsumer = pulsarClient.newConsumer(Schema.JSON(DemoBean.class))
    .topic("persistent://"
        + conf.getTenantName() + "/"
        + conf.getNamespace() + "/"
        + conf.getTopicName())
    .startMessageIdInclusive()
    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
    .subscriptionName("SimplePulsarConsumer")
    {subscription-comment}
    {subscription-type}
    // Define key shared policy for hash range assignment
    .keySharedPolicy(KeySharedPolicy.autoSplitHashRange())
    .subscribe();

...
----

[#use-stickyhashrange]
=== Use stickyHashRange

To set a fixed hash range, use the `stickyHashRange` policy.
This policy requires additional dependencies and producer configuration changes, in addition to the consumer configuration.

. In `src/main/java/com/datastax/pulsar`, create a `SimplePulsarConsumer.java` file with the following contents:
+
.SimplePulsarConsumer.java
[source,java,subs="+attributes"]
----
include::ROOT:partial$simplepulsarconsumer.java[]
----

. Import the following additional classes that are required for the `stickyHashRange` policy:
+
.SimplePulsarConsumer.java
[source,java]
----
import org.apache.pulsar.client.api.Range;
import org.apache.pulsar.client.api.KeySharedPolicy;
import org.apache.pulsar.client.api.SubscriptionType;
----

. In `pulsarConsumer`, add the sticky hash key policy: `.keySharedPolicy(KeySharedPolicy.stickyHashRange().ranges(Range.of(int,int)))`.
+
The following example sets all possible hashes (`0-65535`) on this subscription to one consumer:
+
.SimplePulsarConsumer.java with stickyHashRange for one consumer
[source,java]
----
...

pulsarConsumer = pulsarClient.newConsumer(Schema.JSON(DemoBean.class))
    .topic("persistent://"
        + conf.getTenantName() + "/"
        + conf.getNamespace() + "/"
        + conf.getTopicName())
    .startMessageIdInclusive()
    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
    .subscriptionName("SimplePulsarConsumer")
    {subscription-comment}
    {subscription-type}
    // Policy assigns all possible hashes to one consumer
    .keySharedPolicy(KeySharedPolicy.stickyHashRange().ranges(Range.of(0,65535)))
    .subscribe();

...
----
+
To split the hash range between multiple consumers, add a `Range.of()` argument for each consumer with the assigned hash range.
For example:
+
.SimplePulsarConsumer.java with stickyHashRange for two consumers
[source,java]
----
    // Policy assigns half of the hash range to one consumer and half to another
    .keySharedPolicy(KeySharedPolicy.stickyHashRange().ranges(Range.of(0,32767), Range.of(32768,65535)))
----

. Modify the producer configuration to support `stickyHashRange`:
+
.. In `SimplePulsarProducer.java`, import the following classes:
+
.SimplePulsarProducer.java
[source,java]
----
import org.apache.pulsar.client.api.BatcherBuilder;
import org.apache.pulsar.client.api.HashingScheme;
----

.. Configure the `pulsarProducer` to use the `JavaStringHash` hashing scheme:
+
.SimplePulsarProducer.java
[source,java]
----
pulsarProducer = pulsarClient
    .newProducer(Schema.JSON(DemoBean.class))
    .topic("persistent://"
                + conf.getTenantName() + "/"
                + conf.getNamespace() + "/"
                + conf.getTopicName())
    // Send messages with the same key to the same consumer
    .batcherBuilder(BatcherBuilder.KEY_BASED)
    // Generate hash values for messages based on their keys
    .hashingScheme(HashingScheme.JavaStringHash)
    .create();
----

== Test key shared subscription

include::ROOT:partial$subscription-start-consumer.adoc[]

. In a new terminal window, run `SimplePulsarProducer.java` to begin producing messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 55794190 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 41791865 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 74840732 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 57467766 sent
----
+
In the `SimplePulsarConsumer` terminal, the consumer begins receiving messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":55794190,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":41791865,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
----

. In a new terminal window, try to run a new instance of `SimplePulsarConsumer.java`.
+
If you used `autoSplitHashRange`, then the new consumer subscribes to the topic and consumes messages.
The auto-hashing policy balances hash ranges across available consumers.
+
If you used sticky hashing with one `Range.of()` argument, then the new consumer cannot subscribe to the topic because the `SimplePulsarConsumer` configuration reserved the entire hash range for the first consumer.
For example:
+
.Result when using sticky hashing limited to one consumer
[source,console]
----
[main] INFO com.datastax.pulsar.Configuration - Configuration has been loaded successfully
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - SimplePulsarProducer has been stopped.
Exception in thread "main" java.lang.IllegalStateException: Cannot connect to pulsar
	at com.datastax.pulsar.SimplePulsarConsumer.main(SimplePulsarConsumer.java:59)
Caused by: org.apache.pulsar.client.api.PulsarClientException$ConsumerAssignException: {"errorMsg":"Range conflict with consumer Consumer{subscription=PersistentSubscription{topic=persistent://<tenant>/<namespace>/in, name=SimplePulsarConsumer}, consumerId=0, consumerName=5825b, address=/...}","reqId":1243883448178735299, "remote":"<service_url>", "local":"/192.168.0.95:56512"}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1060)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:101)
	at com.datastax.pulsar.SimplePulsarConsumer.main(SimplePulsarConsumer.java:47)
----
+
To run multiple consumers with sticky hashing, you must modify `SimplePulsarConsumer.java` to split the hash range between consumers, as explained in <<use-stickyhashrange>>.
Then, you can launch multiple instances of `SimplePulsarConsumer.java` to consume messages from different hash ranges.

== See also

* xref:astream-subscriptions.adoc[]
* xref:astream-subscriptions-exclusive.adoc[]
* xref:astream-subscriptions-shared.adoc[]
* xref:astream-subscriptions-failover.adoc[]