= Manage {product} roles and permissions
:navtitle: Manage roles and permissions

You manage role-based access control (RBAC) for {product} through your {astra} organization.
For more information about {astra} RBAC, see xref:astra-db-serverless:administration:rbac.adoc[].

== {astra} roles and permissions for {product}

To access {product}, the minimum required permissions are as follows:

* **{manage-streaming-permission} (`org-stream-manage`)**: Create, read, update, and delete {product} resources in the {astra-ui} and with the APIs.
* **{view-db-permission} (`org-db-view`)**: View the {astra-ui}.
This permission is required for a user to access {product} through the {astra-ui}.
This permission isn't required for programmatic access.

By default, {astra} has no roles that are scoped exclusively to {product}.

The following built-in roles have the {manage-streaming-permission} permission in addition to other permissions:

* {organization-administrator-role}
* {administrator-service-account-role}
* {api-administrator-service-account-role}
* {api-administrator-user-role}

Additionally, you can  xref:astra-db-serverless:administration:custom-roles.adoc[create custom roles] with a narrower set of permissions.
Make sure these roles have the minimum required permissions for {product} ({manage-streaming-permission} and {view-db-permission}), and any other permissions required for the tasks the role needs to perform.
For example, to enable Change Data Capture (CDC), the role also needs permission to manage the relevant databases.

[TIP]
====
To control access to specific streaming tenants, you can set granular xref:astra-db-serverless:administration:custom-roles.adoc#role-scopes[resource scopes] on custom roles.
====

== Authentication and authorization in {pulsar-reg} and {astra}

{pulsar-short} has the concept of https://pulsar.apache.org/docs/security-authorization/[clients with role tokens].
In {pulsar-short}, authentication is the process of verifying a provided token (JWT), and authorization is the process of determining if the role claimed in that token is allowed to complete the requested action.

{product} uses the xref:luna-streaming::index.adoc[{company} distribution of {pulsar}].
This project is an https://github.com/datastax/pulsar[open fork of the {pulsar-reg} project] that maintains feature parity with OSS {pulsar-short}. {product}, as a managed service, abstracts some features/options of {pulsar-short} to ensure continuous, reliable service.

On a shared cluster, your {astra} organization has one or more tenants on a shared {pulsar-short} cluster.
Each of your tenants is secured by {pulsar-short} authentication and authorization models, as well as your {astra} organization's authentication and authorization ({astra} RBAC).

{product} shared clusters are created and administered by {product} administrators.
Each tenant is assigned a custom role and permissions limited to that tenant only.
All tokens created within a tenant are assigned roles similar to the assigning tenant.

For programmatic access, you use {astra} application tokens or {pulsar-short} JWT, depending on the operation you need to perform.
For more information, see xref:operations:astream-token-gen.adoc[].

== See also

* xref:operations:astream-pricing.adoc[]