= Manage {product} roles and permissions
:navtitle: Manage roles and permissions
:page-tag: astra-streaming,security,secure,pulsar

You manage role-based access control (RBAC) for {product} through your {astra-db} organization.
For information about {astra-db} RBAC, including default roles, custom roles, permissions, and user management, see xref:astra-db-serverless:administration:manage-database-access.adoc[].

== {product} permissions

Permissions specific to {product} include the following:

* *Manage Streaming* (`org-stream-manage`): View, add, edit, or remove {product} configurations.

=== Default roles for {product}

There are no default {astra-db} roles specifically scoped to {product}.
However, the following default roles have the *Manage Streaming* permission:

* *Organization Administrator*
* *Administrator Service Account*
* *API Administrator Service Account*
* *API Administrator User*

For information about permissions assigned to default roles, see xref:astra-db-serverless:administration:manage-database-access.adoc[].

=== Custom roles for {product}

If you xref:astra-db-serverless:administration:manage-database-access.adoc#custom-roles[create custom roles] for {product}, those roles must have the following permissions, at minimum:

* *Manage Streaming* (`org-stream-manage`): View and manage {product} in the {astra-ui}.
* *View DB* (`org-db-view`): View the {astra-ui} in general.

Additional permissions might be required, depending on the tasks the role needs to perform.

[TIP]
====
To control access to specific streaming tenants, you can set granular xref:astra-db-serverless:administration:manage-database-access.adoc#role-scopes[resource scopes] on custom roles.
====

== Authentication and authorization in {pulsar-reg} and {astra-db}

{pulsar-short} has the concept of https://pulsar.apache.org/docs/security-authorization/[clients with role tokens].
In {pulsar-short}, authentication is the process of verifying a provided token (JWT), and authorization is the process of determining if the role claimed in that token is allowed to complete the requested action.

{product} uses the {company} version of {pulsar} (xref:luna-streaming::index.adoc[Luna Streaming]).
The https://github.com/datastax/pulsar[Luna project] is an open fork of the {pulsar-short} project that maintains feature parity with OSS {pulsar-short}. {product}, as a managed service, abstracts some features/options of {pulsar-short} to ensure continuous, reliable service.

On a shared cluster, your {astra-db} organization has one or more tenants on a shared {pulsar-short} cluster.
Each of your tenants is secured by {pulsar-short} authentication and authorization models, as well as your {astra-db} organization's authentication and authorization ({astra-db} RBAC).

{product} shared clusters are created and administered by {product} administrators.
Each tenant is assigned a custom role and permissions limited to that tenant only.
All tokens created within a tenant are assigned roles similar to the assigning tenant.

For programmatic access, you use {astra-db} application tokens or {pulsar-short} JWT, depending on the operation you need to perform.
For more information, see xref:operations:astream-token-gen.adoc[].

== See also

* xref:operations:astream-pricing.adoc[]