= Subscriptions in {pulsar-reg}
:navtitle: {pulsar-short} subscriptions overview

_Subscriptions_ in {pulsar-reg} describe which consumers are consuming data from a topic and how they want to consume that data.

== Subscription metadata

Subscriptions are managed in the broker as a collection of metadata about a topic and its subscribed consumers.
This metadata includes:

* Topic name: The topic the consumer wants data from
* Subscription name: A string representing a qualified name for the subscription
* Subscription type: The type of subscription being used
* Subscription cursor: A representation of the consumer's current place in the subscribed topic log

For example, the {pulsar-short} consumer below has a `Shared` subscription to `my-topic` that starts at the `Earliest` cursor position in `my-subscription`:

[source,java]
----
pulsarConsumer = pulsarClient.newConsumer(Schema.BYTES)
    .topic("my-topic")
    .subscriptionName("my-subscription")
    .subscriptionType(SubscriptionType.Shared)
    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
    .subscribe();
----

== Subscription types

* xref:astream-subscriptions-exclusive.adoc[Exclusive subscriptions]
* xref:astream-subscriptions-shared.adoc[Shared subscriptions]
* xref:astream-subscriptions-failover.adoc[Failover subscriptions]
* xref:astream-subscriptions-keyshared.adoc[Key shared subscriptions]

== See also

* xref:getting-started:index.adoc[]
* xref:developing:astream-kafka.adoc[]

