= Failover subscriptions in {pulsar-reg}
:navtitle: Failover
:subscription-comment: // Subscription type is set to Failover
:subscription-type: .subscriptionType(SubscriptionType.Failover)

_Subscriptions_ in {pulsar-reg} describe which consumers are consuming data from a topic and how they want to consume that data.

If an xref:astream-subscriptions-exclusive.adoc[exclusive] consumer fails, the topic backlog accumulates stale, unacknowledged messages.
{pulsar-short} solves this problem with failover subscriptions.
In _failover subscriptions_, {pulsar-short} designates one primary consumer and multiple standby consumers.
If the primary consumer disconnects, the standby consumers begin consuming the subsequent unacknowledged messages.

This page explains how to use {pulsar-short}'s failover subscription model to manage your topic consumption.

== Prerequisites

include::ROOT:partial$subscription-prereq.adoc[]

== Prepare example project and producer

include::ROOT:partial$subscription-setup-project.adoc[]

[#example]
== Create consumer with failover subscription

To create a {pulsar-short} failover subscription, create a `pulsarConsumer` with `{subscription-type}`.

. In `src/main/java/com/datastax/pulsar`, create a `SimplePulsarConsumer.java` file with the following contents:
+
.SimplePulsarConsumer.java
[source,java,subs="+attributes"]
----
include::ROOT:partial$simplepulsarconsumer.java[]
----

== Test failover subscription

include::ROOT:partial$subscription-start-consumer.adoc[]

. In a new terminal window, run `SimplePulsarProducer.java` to begin producing messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 50585599 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 98055337 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 36327100 sent
...
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 73260535 sent
[main] INFO com.datastax.pulsar.SimplePulsarProducer - Message 42372149 sent
----
+
In the `SimplePulsarConsumer` terminal, the primary consumer begins consuming messages:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":50585599,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":98055337,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":36327100,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
----

. In a new terminal window, run a new instance of `SimplePulsarConsumer.java` as a backup consumer.
The backup consumer subscribes to the topic but does not immediately begin consuming messages.

. In your first `SimplePulsarConsumer` terminal, stop the process (`Ctrl+C`), and then switch to your second `SimplePulsarConsumer` terminal.
Notice that the backup consumer begins consuming messages where the first consumer left off:
+
.Result
[source,console]
----
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":73260535,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
[main] INFO com.datastax.pulsar.SimplePulsarConsumer - Message received: {"show_id":42372149,"cast":"LeBron James, Anthony Davis, Kyrie Irving, Damian Lillard, Klay Thompson...","country":"United States","date_added":"July 16, 2021","description":"NBA superstar LeBron James teams up with Bugs Bunny and the rest of the Looney Tunes for this long-awaited sequel.","director":"Malcolm D. Lee","duration":"120 min","listed_in":"Animation, Adventure, Comedy","rating":"PG","release_year":2021,"title":"Space Jam: A New Legacy","type":"Movie"}
----

You can configure as many backup consumers as you like.
To test them, you can progressively end each `SimplePulsarConsumer` process, and then check that the next backup consumer has begun receiving messages.

== See also

* xref:astream-subscriptions.adoc[]
* xref:astream-subscriptions-exclusive.adoc[]
* xref:astream-subscriptions-shared.adoc[]
* xref:astream-subscriptions-keyshared.adoc[]