= What is DataStax {product_name}?
:page-layout: gcx-landing
:slug: what-is-datastax-astra-streaming
:page-aliases: docs@astra-streaming::index.adoc
:page-tag: astra-streaming,planner,admin,dev,pulsar
:navtitle: Astra Streaming
:blank: {empty} +


++++
<div class="landing-row">
++++

[sidebar.landing-card]
.What is {product_name}?
****
--
{product_name} is a cloud native data streaming and event stream processing
service tightly integrated into the Astra cloud platform and powered by Apache Pulsar™.
Using {product_name}, customers can quickly create Pulsar instances,
manage their clusters, scale across cloud regions, and manage Pulsar resources
such as topics, connectors, functions and subscriptions. With {product_name}, customers 
now have powerful capabilities to help drive key business and technical outcomes including:

*Real Time Processing*:: Legacy batch processing jobs result in stale data that
can slow down an entire business.
With {product_name}, customers can capture event data and data changes in real-time,
process that data and take action to create a more responsive, nimble organization.

*Data Science & Machine Learning*:: Today, every business is a data business.
{product_name} allows event data to be stored as a persistent event log which
can be retained indefinitely and played back to refine ML data models or
offloaded to a data lake or other storage for further analysis in the future.

*Modernized Event Driven Architectures*:: {product_name} provides a unified
messaging platform that addresses streaming, pub/sub and queuing use cases with
low latency and at massive scale. Organizations that are struggling to make
their legacy messaging technologies keep up will find {product_name} to be a
frictionless path to modernization.

*Faster Access to Data*:: No one has patience for slow loading web pages or mobile apps.
By combining {product_name} with Astra DB, customers can create read-optimized
views of data that can be quickly read from Astra DB and ensure that data is 
always up to date by leveraging the event stream processing capabilities of {product_name}.
--
--
[link=https://astra.datastax.com, window="_blank"]
image::icons/button-get-started.svg["Get Started button",130]
--
[.landing-card-body-icon]
image::icons/create-db-now.svg["Create a free streaming instance icon",40]
****


++++
</div>
++++


++++
<div class="landing-row">
++++


[sidebar.landing-card]
.{product_name} basics
****
--
New to {product_name}?
Use these tutorials to get familiar with {product_name}.

* xref:streaming-learning:ROOT:index.adoc[]
* xref:getting-started:astream-quick-start.adoc[]
* xref:docs@astra-streaming::astream-code-examples.adoc[]
--
[.landing-card-body-icon]
image::icons/using-the-astra-console.svg["Try out Astra Streaming icon",40]
****


[sidebar.landing-card]
.{product_name} integrations
****
--
{product_name} offers APIs for painlessly integrating existing messaging workloads.

* xref:docs@starlight-jms::index.adoc[Starlight for JMS]
* xref:docs@starlight-kafka::index.adoc[]
* xref:docs@starlight-rabbitmq::index.adoc[]
--
[.landing-card-body-icon]
image::icons/what-is-datastax-luna.svg["Astra DB card icon",40]
****


++++
</div>
++++


++++
<div class="landing-row">
++++

[sidebar.landing-card]
.Sink and source connectors
****
--
{product_name} supports many popular streaming connectors, including:

* xref:streaming-learning:pulsar-io:connectors/sinks/elastic-search.adoc[]
* xref:streaming-learning:pulsar-io:connectors/sinks/kafka.adoc[]
* xref:streaming-learning:pulsar-io:connectors/sinks/snowflake.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[...and more!]
--
[.landing-card-body-icon]
image::icons/connect-clients-to-astra-db.svg[Astra DB card icon,40]
****


[sidebar.landing-card]
.Develop with {product_name}
****
--
Use your favorite developer tools to create applications with {product_name}.

* xref:operations:astream-scrape-metrics.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:developing:astream-kafka.adoc[]
* xref:developing:astream-rabbit.adoc[]

--
[.landing-card-body-icon]
image::icons/connect-clients-to-astra-db.svg[Astra DB card icon,40]
****


[sidebar.landing-card]
.Manage your {product_name} instance
****
--
Manage your cluster's security and deployment.

* xref:operations:astream-georeplication.adoc[]
* xref:operations:astream-regions.adoc[]
--
[.landing-card-body-icon]
image::icons/security.svg[Astra DB card icon,40]
****

++++
</div>
++++

== Do more with Astra

++++
<div class="landing-row">
++++

[sidebar.landing-card]
.{astra_db}
****
--
DataStax Astra DB is a serverless, multi-cloud database service built on Apache Cassandra® that is optimized for real-time applications that require large data volume, low latency, and flexible data models.

https://docs.datastax.com/en/astra-serverless/docs/index.html[Astra DB]
--
[.landing-card-body-icon]
image::icons/what-is-astra-streaming.svg[Astra DB card icon,40]
****


[sidebar.landing-card]
.Change Data Capture
****
--
Change Data Capture (CDC) for {product_name} enables you to send data changes in real time throughout your entire ecosystem.
With a wide range of connectors to data warehouses, messaging systems, data lakes as well as client libraries, you can send your data wherever it needs to go in real time.

xref:developing:astream-cdc.adoc[]
--
[.landing-card-body-icon]
image::icons/migrating-apps.svg[Astra DB card icon,40]
****

[sidebar.landing-card]
.DataStax Astra Block for Ethereum
****
--
With the DataStax Astra Block for Ethereum, you can stream a set of sanitized Ethereum data sets into your Astra database in real-time.

https://docs.datastax.com/en/astra-serverless/docs/block/overview.html[Astra Block for Ethereum]
--
[.landing-card-body-icon]
image::icons/avoid-cloud-lockin.svg[Astra DB card icon,40]
****

++++
</div>
++++


++++
<div class="landing-row">
++++

[sidebar.landing-card]
.Awesome Astra
****
--
In addition to this {product_name} documentation, be sure to check out our new https://awesome-astra.github.io/docs/[Awesome-Astra, window="_blank"] site.
It includes developer-focused tutorials and learning materials to help you quickly build great applications.
Awesome-Astra also provides a rich set of external tools to connect your apps to {product_name} data, and "Try It!" features within the product's API docs.
Get a jump on your learning and start coding today!
--
****

++++
</div>
++++

{blank}

'''