= {product}
:page-layout: landing
:data-uri:

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="grid lg:grid-rows-1 lg:grid-cols-2 gap-6 mt-6">

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 flex p-2">
        svg:ROOT:using-the-astra-console.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Astra Streaming</h3>

    Delivered as a fully-managed data streaming and event stream processing service with boundless scale, massive throughput, and low latency, {product} is the simplest way to modernize your event driven architecture and turbo charge your data in motion strategy.
    You can create {pulsar-short} instances, scale across cloud regions, and manage {pulsar-short} resources such as topics, connectors, functions and subscriptions.

    xref:astra-streaming:getting-started:index.adoc[Get started with Astra Streaming]

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 flex p-2">
        svg:ROOT:what-is-astra-db.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <h3 class="discrete !text-h2 !m-0 [&>a]:text-white">APIs and integrations</h3>

    <p>{product} goes beyond the {astra-ui}. You can use xref:apis:index.adoc[{product} APIs], xref:developing:clients/index.adoc[{pulsar} clients], and related tools to manage your streaming tenants and resources, develop applications, and xref:connectors:index.adoc[integrate] with popular sinks and sources.</p>

  </div>

</div>

<div class="grid lg:grid-rows-1 lg:grid-cols-3 gap-6 mt-6">

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:connect-clients-to-astra-db.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Real Time Processing</h3></div>

    Legacy batch processing jobs result in stale data that can slow down an entire business.
    With {product}, customers can capture event data and data changes in real-time,
    process that data and take action to create a more responsive, nimble organization.

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:migrating-apps.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Event Driven Architecture</h3></div>

    {product} provides a unified messaging platform that addresses streaming,
    pub/sub and queuing use cases with low latency and at massive scale.
    Organizations that need to maintain legacy messaging technologies will find {product} to be a
    frictionless path to modernization.

  </div>

  <div class="flex flex-col items-start gap-4 rounded border p-4">

    <div class="rounded bg-level1 p-2">
        svg:ROOT:what-is-astra-streaming.svg[role="mx-auto my-auto w-8 h-8"]
    </div>

    <div><h3 class="discrete !text-h2 !m-0 [&>a]:text-white">Change Data Capture</h3></div>

    xref:developing:astream-cdc.adoc[Change Data Capture (CDC)] enables you to send data changes in real time throughout your entire ecosystem.
    With a wide range of connectors to data warehouses, messaging systems, data lakes as well as client libraries, you can send your data wherever it needs to go in real time.

  </div>

</div>

++++