= {astra_cli} overview
:navtitle: {astra_cli}
:description: {astra_cli} provides a one-stop shop for managing your Astra resources through scripts or commands in your local terminal.

The xref:astra-cli:ROOT:index.adoc[{astra_db} Command-Line Interface ({astra_cli})] is a set of commands you can use to create and manage {astra_db} and {product} resources:

* Creation and management of {astra_db} databases, {astra_stream} tenants, and their associated artifacts.
* Querying and data loading.
* Organization and user management.
* Security and token configuration.

{astra_cli} commands are available for {astra_db} and {astra_stream}.
They're designed to get you working quickly, with an emphasis on automation.

For example, the following command creates a Pulsar tenant:

[source,bash,subs="+quotes"]
----
astra streaming create **TENANT_NAME** --cloud **CLOUD_PROVIDER** --region **REGION_NAME** --plan **PLAN_TYPE** --namespace **TENANT_INITIAL_NAMESPACE_NAME**
----

You can use {astra_cli} instead of or in addition to the {astra_ui} and {astra_db} APIs.

For more information, see the following:

* xref:api-reference:databases.adoc[]
* https://www.datastax.com/blog/introducing-cassandra-astra-cli[Accelerate your Cassandra development and automation with the {astra-cli}]
