= {starlight_rabbitmq}
:page-tag: starlight-rabbitmq,quickstart,admin,dev,pulsar

{starlight_rabbitmq} brings native RabbitMQ(R) protocol support to {pulsar-reg}, enabling migration of existing RabbitMQ applications and services to {pulsar-short} without modifying the code.
RabbitMQ applications can leverage {pulsar-short} features such as the following:

* *Consistent metadata store*: {starlight_rabbitmq} uses Apache ZooKeeper(TM), so existing Zookeeper configuration stores can store {starlight_rabbitmq} metadata.
* *Security and authentication*: {starlight_rabbitmq} connects to brokers that have TLS, authentication, and/or authorization enabled, because it uses the same `AuthenticationService` as {pulsar-short}.
* *Clustering*: Launch multiple stateless {starlight_rabbitmq} instances simultaneously for scalability and high availability.
* *Multi-tenancy*: {starlight_rabbitmq} offers support for multi-tenancy, mapping an AMQP virtual host to a {pulsar-short} tenant and namespace.

By integrating two popular event streaming ecosystems, {starlight_rabbitmq} unlocks new use cases and reduces barriers for users adopting {pulsar-short}. Leverage advantages from each ecosystem and build a truly unified event streaming platform with {starlight_rabbitmq} to accelerate the development of real-time applications and services.

Get started producing and consuming RabbitMQ messages on a {pulsar-short} cluster.

== {starlight_rabbitmq} Quickstart

. To start connecting {starlight_rabbitmq}, select *RabbitMQ* in the {product} *Connect* tab.

. When the popup appears, confirm you want to enable RabbitMQ on your tenant.
+
[IMPORTANT]
====
You can't remove the RabbitMQ namespace created on your tenant with this step.
You must remove the tenant itself to remove this namespace.
====

. Select *Enable RabbitMQ* to create a `rabbitmq` namespace in your {product} tenant for RabbitMQ functionality, as well as a configuration file.

. Save the configuration to a `rabbitmq.conf` file:
+
.rabbitmq.conf
[source,plain,subs="+quotes"]
----
username: **TENANT_NAME**
password: token:***
host: rabbitmq-azure-us-west-2.streaming.datastax.com
port: 5671
virtual_host: azure/rabbitmq
----
+
The configuration details depend on your {product} tenant configuration.

== Connect RabbitMQ and {pulsar-short}

This example uses a Python script to create a connection between RabbitMQ and your {pulsar-short} tenant, establish a message queue named `queuename`, print ten messages, and then close the connection.

. Create a `connect-test.py` file containing the following code:
+
.connect-test.py
[source,python,subs="+quotes"]
----
import ssl
import pika

virtual_host = "**VIRTUAL_HOST**"
token = "**TOKEN**"

context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.verify_mode = ssl.CERT_NONE
context.check_hostname = False
context.load_default_certs()
ssl_options = pika.SSLOptions(context)

connection = pika.BlockingConnection(pika.ConnectionParameters(
    virtual_host=virtual_host,
    host="**HOST_NAME**",
    ssl_options=ssl_options,
    port=**PORT**,
    credentials=pika.PlainCredentials("", token)))
print("connection success")

channel = connection.channel()
print("started a channel")

channel.queue_declare(queue='queuename')

for x in range(10):
    channel.basic_publish(exchange='',
                      routing_key='routingkey',
                      body='message body goes here')
    print(" sent one")

connection.close()
----
+
Replace the following with values from your downloaded `rabbitmq.conf` file:
+
* `**VIRTUAL_HOST**`
* `**TOKEN**`
* `**HOST_NAME**`
* `**PORT**`

. Save the `connect-test.py` file.

. Run `connect-test.py`:
+
[source,shell]
----
python3 connect-test.py
----

. Make sure the result is similar to the following:
+
[source,console]
----
connection success
started a channel
 sent one
 sent one
 sent one
 sent one
 sent one
 sent one
 sent one
 sent one
 sent one
 sent one
----

. Navigate to your `rabbitmq` namespace dashboard in {product}, and then monitor your activity.
+
If configured correctly, you should have new topics called `amq.default.__queuename` and `amq.default_routingkey` that were created by the Python script, as well as an increasing amount of traffic and messages.
Your RabbitMQ messages are being published to a {pulsar-short} topic.

== RabbitMQ exchanges and {pulsar-short} topics

{starlight_rabbitmq} maps RabbitMQ _exchanges_ to {pulsar-short} _topics_, as described in the following table:

[cols="1,1,1,1"]
|===
|Exchange |Routing key |{pulsar-short} topic name |Usage example

|`amp.direct`
|used
|`amq.direct.__{routing key}`
|`channel.basic_publish(exchange='amp.direct',`

|`amp.default` or empty string
|used
|`amq.default.__{routing key}`
|`channel.basic_publish(exchange="),`

|`amp.match`
|not used
|`amp.match`
|`channel.basic_publish(exchange=amp.match),`

|`amp.fanout`
|not used
|`amp.fanout`
|`channel.basic_publish(exchange='amp.fanout'),`

|`headers`
|not used
|Name of the header
|`channel.exchange_declare(exchange='header_logs', exchange_type='headers')
channel.basic_publish(exchange='header_logs'),`

|===

== See also

* https://github.com/datastax/starlight-for-rabbitmq[{company} {starlight_rabbitmq} project]
* xref:getting-started:index.adoc[]
* xref:astream-kafka.adoc[{starlight_for_astra}]