=  Use {pulsar-reg} binaries with {product}
:navtitle: Configure the {pulsar-short} CLI
:description: Download a compatible {pulsar-short} artifact and configure the binaries for use with {product}.

{product} runs a {company} version of {pulsar-reg}.
The benefits of OSS {pulsar-short} are also available in {product}.

To get started, you must download a compatible {pulsar-short} artifact, and then configure the binaries for use with {product}.

== Download a compatible artifact

{product} is compatible with {pulsar-short} version {pulsar-version}.

. Download the binaries for the https://pulsar.apache.org/download/[latest {pulsar-version} patch release]:
+
[source,shell,subs="+quotes,+attributes"]
----
PULSAR_VERSION="{pulsar-version}.**PATCH**"
wget https://archive.apache.org/dist/pulsar/pulsar-$PULSAR_VERSION/apache-pulsar-$PULSAR_VERSION-bin.tar.gz
----

. Extract the downloaded artifact:
+
[source,shell]
----
tar xvfz apache-pulsar-$PULSAR_VERSION-bin.tar.gz
----
+
The resulting directory is named `apache-pulsar-**PULSAR_VERSON**`.
This directory is known as the _{pulsar-short} folder_.
{pulsar-short} guides assume you are working within this directory.
{pulsar-short} commands prefixed by `./bin` indicate the command is run from within the {pulsar-short} folder.

== Configure binaries for {product}

There are several files and folders in the {pulsar-short} folder.
The two most important folders are `/conf` and `/bin`.

The executables in `/bin` use the configurations in `/conf` to run commands.

Each tenant you create in {product} comes with its own custom configuration for SSO, endpoints, and so on.
You must download the tenant configuration from {product}, and then overwrite the `./conf/client.conf` file.

. In the {astra_ui} navigation menu, click *Streaming*, and then select your tenant.

. Click the *Connect* tab, in the *{pulsar-short} CLI* section, click *Download client.conf*.

. Save the file in `apache-pulsar-**PULSAR_VERSION**/conf`.
This overwrites the default `client.conf` in the `/conf` folder.

. With your {product} tenant's configuration in place, use the binaries to interact with a {pulsar-short} cluster:
+
* `./bin/pulsar-admin`: Administrative commands to manage namespaces, topics, functions, connectors, and so on
* `./bin/pulsar-client`: Interactive commands for producing and consuming messages
+
For a full reference of all commands within the CLI, see the https://pulsar.apache.org/docs/reference-cli-tools/[{pulsar-short} CLI documentation].

== Validate the connection

Run some commands to validate the binary configuration.

. List all tenants:
+
[source,shell]
----
./bin/pulsar-admin tenants list
----

. Produce a message:
+
[source,shell,subs="+quotes"]
----
./bin/pulsar-client produce **TENANT_NAME**/**NAMESPACE_NAME**/**TOPIC_NAME** --messages "Hi there" --num-produce 1
----

== See also

* xref:produce-consume-astra-portal.adoc[]
* xref:produce-consume-pulsar-client.adoc[]