= Produce and consume messages in the {astra-ui}
:navtitle: Test tenants in the {astra-ui}
:description: Use this guide to create and consume a topic message using the {astra-ui}.

To verify that your {product} tenant can produce and consume messages, you can use the **Try Me** feature in the {astra-ui}.

== Prerequisites

You need an {product} tenant with at least one namespace and two topics (one for the producer and one for the consumer).
For instructions, see the xref:getting-started:index.adoc[{product} quickstart] or xref:operations:create-delete-tenants.adoc[].

== Produce and consume a test message

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant.

. Click the **Try Me** tab.

. Select a namespace, producer topic, and consumer topic for the test.

. For this example, use the default values for the **Connection type**, **Read position**, **Subscription**, and **Subscription Type** settings.
In future tests, you might want to change these settings.

. Click *Connect* to open a websocket connection in your browser with the producer topic.

. In the *Send message* field, enter a test message, and then click *Send*.

A message is produced (sent) to your selected producer topic, and then the consumer topic consumes (retrieves) the message.
Produced and consumed messages are printed in a chat style format in the **Test Message** dialog.

== See also

* xref:astream-functions.adoc[]
* xref:astream-cdc.adoc[]