= Produce and consume messages in the {astra-ui}
:navtitle: {astra-ui}
:description: Use this guide to create and consume a topic message using the {astra-ui}.

This guide assumes you have completed the xref:getting-started:index.adoc[{product} quickstart].

Now, it's time to produce and consume messages in your new streaming tenant.
The following steps will use the "Try Me" feature of the {astra-ui} to interact with an existing topic.

== Select the producer and consumer topics

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant.

. Click the **Try Me** tab.

. Select a namespace, producer topic, and consumer topic for the test.

. For this example, you can use the default values for the **Connection type**, **Read position**, **Subscription**, and **Subscription Type** settings.
+
In future tests, you might want to change these settings.

== Connect and send a message

. Click *Connect* to open a websocket connection in your browser with this topic.

. In *Send message*, type a message for the test, and then click *Send*.

A message is produced (sent) to your selected topic, and then the consumer consumes (retrieves) the message.
Produced and consumed messages are printed in a chat style format in the **Test Message** dialog.

== See also

* xref:astream-functions.adoc[]
* xref:astream-cdc.adoc[]