= {product} quickstart

{product} is a serverless data streaming and event stream processing service integrated in the {astra-ui} and powered by {pulsar-reg}.
Using {product}, you can create {pulsar-short} instances, manage streaming clusters, scale across cloud regions, and manage {pulsar-short} resources such as topics, connectors, functions and subscriptions.

This quickstart demonstrates how to create and use a streaming tenant running {pulsar-short}.

== Prerequisites

* An active {astra-url}[{product-short} account^]

== Create a streaming tenant

An {product} tenant is a portion of {company}-managed {pulsar} that is only yours.
Within tenants, you create namespaces, topics, functions, and more.
To learn more about the concept of tenancy, see the https://pulsar.apache.org/docs/concepts-multi-tenancy/[{pulsar-short} documentation].

You can create a tenant in the {astra-ui} or programmatically.
For this quickstart, use the {astra-ui}.

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click *Create tenant*.

. Name your streaming tenant something memorable like `my-stream-**RANDOM_UUID**`.
All tenant names in {product} must be unique.
`**RANDOM_UUID**` can be any string of letters and numbers, as long as it is unique.

. Choose your preferred cloud provider and region.
For this example tenant, the region doesn't really matter.

. Click *Create tenant*.
When the tenant is ready, it appears on the *{product}* dashboard.
Click the tenant's name to inspect and configure it.

== Create a namespace in your tenant

Namespaces are logical groupings, such as environments or applications, for message topics within tenants.

{product} automatically creates a `default` namespace when you create a tenant.
You can use the default namespace or create other namespaces.
Tenants usually have many namespaces.
To learn more about namespaces, see the https://pulsar.apache.org/docs/concepts-messaging/#namespaces[{pulsar-short} documentation].

You can create namespaces in the {astra-ui} or programmatically.
For this quickstart, use the {astra-ui}.
For information about the {pulsar-short} CLI or APIs, see xref:developing:configure-pulsar-env.adoc[] and xref:developing:using-curl.adoc[].

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant.

. Click the *Namespace And Topics* tab, and then click *Create Namespace*.

. Enter a namespace name, and then click *Create Namespace*.
The new namespace appears in the *Namespaces And Topics* list.

== Create a topic

Topics are the core construct of a messaging system.
Topics provide a way to group messages matching certain criteria.

The name of the topic usually broadly defines the criteria.
You can also apply more advanced characteristics, like schemas, at the topic level.

Topics are where other applications or services can "listen" for new messages.
Consumers subscribe to topics to receive messages, and functions and connectors can listen for messages to trigger automated workflows.

In {pulsar-short}, topic addresses are formatted like URLs, such as `persistent://tenant/namespace/topic`.
To learn more about topics, see the https://pulsar.apache.org/docs/concepts-messaging/#topics[{pulsar-short} documentation].

As in the previous steps, you can create topics in the {astra-ui} or programmatically.

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant.

. Click the *Namespace And Topics* tab.

. Find the namespace where you want to create a topic, and then click *Add Topic*.

. Enter a topic name, and then click *Add Topic*.
+
Topic names must start with a lowercase letter, and they can contain only letters, numbers, and hyphens (`-`).
+
Disregard the https://pulsar.apache.org/docs/concepts-messaging/#partitioned-topics[*Persistent* and *Partitioned*] options for now.

== Next steps

Your new topic is ready to produce and consume messages.
There are several different ways to do this:

* xref:developing:produce-consume-astra-portal.adoc[{astra-ui}]: Use {product}'s **Try Me** feature in the {astra-ui}.
* xref:developing:produce-consume-pulsar-client.adoc[{pulsar-short} Client]: Use the {pulsar-short} CLI to interact with the topic.
* xref:developing:clients/index.adoc[Runtime Clients]: Create a client application that interacts with {pulsar-short}.