= Activate Flink

[NOTE]
====
This guide is part of a series for building streaming applications with {product_name} and Apache Flink. The other guides in the series are:

* xref:flink/index.adoc[]
* xref:flink/create.adoc[]
* xref:flink/manage.adoc[]
====
The {product_name} Flink endpoint is available at `https://api.dev.streaming.datastax.com/flink/api/`.

The endpoint is currently *only* available in the aws-us-east2 region, so its full name is `https://pulsar-aws-useast2.api.dev.streaming.datastax.com/flink/api/`.

To connect, you'll need a Streaming tenant, an AstraCS token, and a Pulsar token.
For more, see xref:getting-started:index.adoc[].

. Set your environmental variables to follow along with the examples in this section:
+
[source,bash]
----
TOKEN=AstraCS:xxxx
TENANT=flink-tenant
PULSAR_CLIENT_CONF=$(realpath client.conf)
PULSAR_TOKEN=eyXXXX
ENDPOINT="https://pulsar-aws-useast2.api.dev.streaming.datastax.com/flink/api/jobs/$TENANT"
----

. Activate Flink in {product_name} with a POST request:
+
[tabs]
====
Curl::
+
--
[source,bash]
----
curl -H "Content-Type: application/json" \
-H "Authorization: Bearer $PULSAR_TOKEN" \
-X POST "https://pulsar-aws-useast2.api.dev.streaming.datastax.com/flink/$TENANT"
----
--

Result::
+
--
[source,]
----
{"status":true}%
----
--
====

. Test connectivity by issuing a GET request for a list of your current Flink jobs:
+
[tabs]
====
Curl::
+
--
[source,bash]
----
curl -H "Content-Type: application/json" \
-H "Authorization: Bearer $TOKEN" "https://pulsar-aws-useast2.api.dev.streaming.datastax.com/flink/api/jobs/$TENANT"
----
--

Result::
+
--
[source,bash]
----
[]%  //empty array
----
--
====

Now that you've connected {product_name} and Flink, you can create your Flink job.

== What's next?

* xref:flink/create.adoc[]
* xref:flink/manage.adoc[]
* xref:flink/index.adoc[]