= Manage Flink jobs in Astra Streaming

[NOTE]
====
This guide is part of a series for building streaming applications with {product_name} and Apache Flink. The other guides in the series are:

* xref:flink/index.adoc[]
* xref:flink/connect.adoc[]
* xref:flink/create.adoc[]

You will need your flink endpoint address within Astra Streaming. If you don't have this, please contact the team at streaming@datastax.com or open a support ticket asking for this info.
====

== List current Flink jobs
Issue a GET request for a list of your current Flink jobs

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>

curl -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/api/jobs/$TENANT_NAME
----
--

Result::
+
--
[source,bash]
----
[]  //empty array
----
--
====

== Check a Flink job's status
Issue a GET request with the job name:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  "https://<FLINK_ENDPOINT_ADDRESS>/flink/api/jobs/$TENANT_NAME/$JOB_NAME
----
--

Result::
+
--
[source,json]
----
{
  "specs": {
    "name": "j-flink-tenant-zicjos",
    "outputTable": "output",
    "selectQuery": "select input.name from flink.input as input",
    "createTableSpecs": [
      {
        "tableName": "input",
        "columns": [
          "name string"
        ],
        "topic": "flink-tenant/flink/persons",
        "format": "json"
      }
    ],
    "parallelism": 1
  },
  "status": {
    "state": "RECONCILING",
    "error": "{\"type\":\"org.apache.flink.kubernetes.operator.exception.DeploymentFailedException\",\"message\":\"back-off 5m0s restarting failed container=flink-main-container pod=j-flink-tenant-zicjos-84c46c749-pmbfw_fl-flink-tenant(bcaf73fd-0db7-4a5d-897b-63acad0822c3)\",\"additionalMetadata\":{\"reason\":\"CrashLoopBackOff\"},\"throwableList\":[]}",
    "lifecycleState": "DEPLOYED"
  }
}
----
--
====

Aww, it failed! Let's see what happened with the logs.

== View a Flink job's logs

To tail a Flink job's logs:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/logs/$TENANT_NAME/$JOB_NAME/jobmanager?tail=true
----
--

Result::
+
--
[source,bash]
----
2023-05-26T16:18:34.831498931Z 2023-05-26 16:18:34,831 INFO  org.apache.flink.runtime.jobmaster.MiniDispatcherRestEndpoint [] - Shutting down rest endpoint.
2023-05-26T16:18:35.245317915Z 2023-05-26 16:18:35,244 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator        [] - Shutting down remote daemon.
2023-05-26T16:18:35.247440899Z 2023-05-26 16:18:35,247 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator        [] - Remote daemon shut down; proceeding with flushing remote transports.
2023-05-26T16:18:35.252706981Z WARNING: An illegal reflective access operation has occurred
2023-05-26T16:18:35.252794333Z WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:/tmp/flink-rpc-akka_f43af027-e758-46fa-9ee5-bee1a0a16278.jar) to method java.nio.DirectByteBuffer.cleaner()
2023-05-26T16:18:35.252817286Z WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
2023-05-26T16:18:35.252820857Z WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2023-05-26T16:18:35.252824430Z WARNING: All illegal access operations will be denied in a future release
2023-05-26T16:18:35.262710744Z 2023-05-26 16:18:35,261 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator        [] - Remoting shut down.
2023-05-26T16:18:35.264677449Z 2023-05-26 16:18:35,264 INFO  akka.remote.RemoteActorRefProvider$RemotingTerminator        [] - Remoting shut down.
* Connection #0 to host pulsar-aws-useast2.api.dev.streaming.datastax.com left intact
----
--
====

== Delete a Flink job

To delete a Flink job:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  -X DELETE \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/$JOB_NAME
----
--

Result::
+
--
[source,bash]
----
200 success
----
--
====

== What's next?

* xref:flink/connect.adoc[]
* xref:flink/create.adoc[]
* xref:flink/index.adoc[]
