= Manage Flink jobs in Astra Streaming

[NOTE]
====
This guide is part of a series for building streaming applications with {product_name} and Apache Flink. The other guides in the series are:

* xref:flink/index.adoc[]
* xref:flink/connect.adoc[]
* xref:flink/create.adoc[]

You will need your flink endpoint address within Astra Streaming. If you don't have this, please contact the team at streaming@datastax.com or open a support ticket asking for this info.
====

== List current Flink jobs
Issue a GET request for a list of your current Flink jobs

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>

curl -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/api/jobs/$TENANT_NAME
----
--

Result::
+
--
[source,bash]
----
[]  //empty array
----
--
====

== Check a Flink job's status
Issue a GET request with the job name:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  "https://<FLINK_ENDPOINT_ADDRESS>/flink/api/jobs/$TENANT_NAME/$JOB_NAME
----
--

Result::
+
--
[source,json]
----
{
  "specs": {
    "name": "j-flink-tenant-zicjos",
    "outputTable": "output",
    "selectQuery": "select input.name from flink.input as input",
    "createTableSpecs": [
      {
        "tableName": "input",
        "columns": [
          "name string"
        ],
        "topic": "flink-tenant/flink/persons",
        "format": "json"
      }
    ],
    "parallelism": 1
  },
  "status": {
    "state": "RECONCILING",
    "error": "{\"type\":\"org.apache.flink.kubernetes.operator.exception.DeploymentFailedException\",\"message\":\"back-off 5m0s restarting failed container=flink-main-container pod=j-flink-tenant-zicjos-84c46c749-pmbfw_fl-flink-tenant(bcaf73fd-0db7-4a5d-897b-63acad0822c3)\",\"additionalMetadata\":{\"reason\":\"CrashLoopBackOff\"},\"throwableList\":[]}",
    "lifecycleState": "DEPLOYED"
  }
}
----
--
====

Aww, it failed! Let's see what happened with the logs.

== View a Flink job's logs

To tail a Flink job's logs:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
TENANT_NAME=<YOUR_ASTRA_STREAMING_TENANT_NAME>
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/logs/$TENANT_NAME/$JOB_NAME/jobmanager?tail=true
----
--

Result::
+
--
[source,bash]
----
no default tenant admin role is defined
----
--
====

== Delete a Flink job

To delete a Flink job:

[tabs]
====
Curl::
+
--
[source,bash]
----
ASTRA_TOKEN=AstraCS:XXXX
JOB_NAME=j-flink-tenant-zicjos

curl -v -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ASTRA_TOKEN" \
  -X DELETE \
  https://<FLINK_ENDPOINT_ADDRESS>/flink/$JOB_NAME
----
--

Result::
+
--
[source,bash]
----
200 success
----
--
====

== What's next?

* xref:flink/connect.adoc[]
* xref:flink/create.adoc[]
* xref:flink/index.adoc[]
