= Use the {product} {devops-api}
:description: Learn about the {product} {devops-api}.

The {product} {devops-api} is one of the APIs that you can use to manage your {pulsar-reg} tenants and their resources.
Use this API to manage higher-level {product} objects associated with your {product-short} organization, such as the Change Data Capture (CDC) settings, {pulsar-short} tenants, geo-replications, {pulsar-short} stats, and {pulsar-short} tokens.

This page summarizes commonly used endpoints.
For more information and all endpoints, see the xref:astra-streaming:apis:attachment$devops.html[{product} {devops-api} specification reference].

Other available APIs include the xref:apis:api-operations.adoc[{product} {pulsar-short} Admin API] and the xref:developing:using-curl.adoc[OSS {pulsar-reg} REST APIs].

== Prerequisites

To use the {product} {devops-api}, you need the following:

* An active {product-short} account with access to {product}.
* An xref:operations:astream-token-gen.adoc[{product-short} application token].
* Depending on the operations you need to perform, you might need additional information about your tenant.
You can get this information with `<<get-tenant-information,GET 'https://api.astra.datastax.com/v2/streaming/tenants'>>` or from the xref:operations:create-delete-tenants.adoc#get-tenant-information[**Tenant Details** section in the {astra-ui}].

=== Set environment variables

Due to their frequency in {product} {devops-api} calls, you might find it helpful to set the following environment variables:

[source,bash,subs="+quotes"]
----
export NAMESPACE="**NAMESPACE_NAME**"
export TENANT="**TENANT_NAME**"
export TOPIC="**TOPIC_NAME**"
export ASTRA_TOKEN="**ASTRA_APPLICATION_TOKEN**"
----

The examples in this guide use environment variables for these values.
For example:

//FIX the intro for all devops api code samples per below.
//Use double quotes around paths
[source,curl]
----
curl -sS -L -X GET "https://api.astra.datastax.com/v2/streaming/tenants" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
| python3 -mjson.tool
----

=== Format responses

include::ROOT:partial$format-api-response.adoc[]


//Bring devops api code samples from api-operations.adoc


[#astra-streaming-devops-api-tenant-operations]
== {product} {devops-api} tenant operations

The following examples demonstrate how to use the {product} {devops-api} to manage {product} resources.

[#get-tenant-information]
=== Get tenant information

[source,curl]
----
curl --location --request GET 'https://api.astra.datastax.com/v2/streaming/tenants' --header "Authorization: Bearer $ASTRA_TOKEN" | python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,console]
----
[
    {
        "id": "14b77c47-bdfd-4ba1. . .",
        "tenantName": "mytenant",
        "clusterName": "pulsar-aws-useast2",
        "webServiceUrl": "https://pulsar-aws-useast2",
        "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
        "websocketUrl": "wss://pulsar-aws-useast2:8001/ws/v2",
        "websocketQueryParamUrl": "wss://pulsar-aws-useast2:8964/ws/v2",
        "pulsarToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpX…..",
        "plan": "payg",
        "planCode": "1",
        "astraOrgGUID": "b282a256-b129-......",
        "cloudProvider": "aws",
        "cloudProviderCode": "1",
        "cloudRegion": "useast2",
        "status": "active",
        "jvmVersion": "JDK11",
        "pulsarVersion": "2.10.2",
        "regionZone": "na",
        "Email": "",
        "userMetricsUrl": "https://prometheus-aws-useast2….",
        "pulsarInstance": "prod0"
    },
    {
        "id": "e8bf25d8-a6a1-4169-. . .",
        "tenantName": "mytenant2",
        "clusterName": "pulsar-gcp-useast1",
        "webServiceUrl": "https://pulsar-gcp-useast1",
        "brokerServiceUrl": "pulsar+ssl://pulsar-gcp-useast1:6651",
        "websocketUrl": "wss://pulsar-gcp-useast1m:8001/ws/v2",
        "websocketQueryParamUrl": "wss://pulsar-gcp-useast1:8964/ws/v2",
        "pulsarToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.ey. . .",
        "plan": "payg",
        "planCode": "1",
        "astraOrgGUID": "b282a256-b129-43e9. . .",
        "cloudProvider": "gcp",
        "cloudProviderCode": "2",
        "cloudRegion": "useast1",
        "status": "active",
        "jvmVersion": "JDK11",
        "pulsarVersion": "2.10.2",
        "regionZone": "na",
        "Email": "",
        "userMetricsUrl": "https://prometheus-gcp-useast1. . .",
        "pulsarInstance": "prod0"
    }
]
----
====

=== Get {product} cloud providers and regions

[source,curl]
----
curl --location --request GET 'https://api.astra.datastax.com/v2/streaming/providers' --header "Authorization: Bearer $ASTRA_TOKEN" | python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,console]
----
{
    "aws": [
        "useast1",
        "uswest2",
        "useast2"
    ],
    "azure": [
        "westus2",
        "eastus",
        "australiaeast"
    ],
    "gcp": [
        "useast1",
        "uscentral1",
        "australiase1",
        "europewest1",
        "useast4"
    ]
}
----
====

[#create-a-tenant]
=== Create a tenant

Create a tenant:

[source,curl]
----
curl --location --request POST 'https://api.astra.datastax.com/v2/streaming/tenants' --header 'Content-Type: application/json' --header "Authorization: Bearer $ASTRA_TOKEN" --data-raw '{
 	"cloudProvider": "aws",
 	"cloudRegion": "useast2",
 	"tenantName": "mytenant",
 	"userEmail": "joshua@example.com"
 }' | python3 -mjson.tool
----

Create a tenant with file input:

[source,curl]
----
curl --fail --location --request POST 'https://api.astra.datastax.com/v2/streaming/tenants' --header 'Content-Type: application/json' --header "Authorization: Bearer $ASTRA_TOKEN" --data "@mytenant-config.json" | python3 -mjson.tool
----

.Result
[%collapsible]
====
The output includes the "pulsarToken" which is the JWT for this {pulsar-short} instance.

[source,console]
----
{
    "namespace": "default",
    "topic": "",
    "id": "",
    "tenantName": "mytenant",
    "clusterName": "pulsar-aws-useast2",
    "webServiceUrl": "https://pulsar-aws-useast2",
    "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
    "websocketUrl": "wss://pulsar-aws-useast2:8001/ws/v2",
    "websocketQueryParamUrl": "wss://pulsar-aws-useast2:8964/ws/v2",
    "pulsarToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9. . .",
    "plan": "payg",
    "planCode": "",
    "astraOrgGUID": "b282a256-b129-43e9. . .",
    "cloudProvider": "aws",
    "cloudProviderCode": "",
    "cloudRegion": "useast2",
    "status": "active",
    "jvmVersion": "JDK11",
    "pulsarVersion": "2.10.2",
    "regionZone": "",
    "Email": "",
    "userMetricsUrl": "",
    "pulsarInstance": ""
}
----
====

[#delete-a-tenant]
=== Delete a tenant

[source,curl]
----
curl --location --request DELETE 'https://api.astra.datastax.com/v2/streaming/tenants/{tenant}/clusters/{cluster}' --header 'Content-Type: application/json' --header "Authorization: Bearer $ASTRA_TOKEN"
----

A successful request returns either no response or `202 Accepted`.

If unsuccessful, returns `404 Not Found` or other error code.



== {product} {devops-api} geo-replication operations

For more information about geo-replication, see xref:operations:astream-georeplication.adoc[].

=== Get status of geo-replication

[source,curl]
----
curl --location --fail --request GET "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" --header "Authorization: Bearer $ASTRA_TOKEN" | python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,console]
----
{
    "pulsarInstance": "prod0",
    "tenant": "mytenant",
    "namespace": "mynamespace",
    "replications": {
        "pulsar-aws-useast2": [
            "pulsar-aws-uswest2",
            "pulsar-aws-useast2"
        ],
        "pulsar-aws-uswest2": [
            "pulsar-aws-uswest2",
            "pulsar-aws-useast2"
        ]
    },
    "clusters": {
        "pulsar-aws-useast2": {
            "clusterName": "pulsar-aws-useast2",
            "cloudProvider": "aws",
            "cloudRegion": "useast2",
            "clusterType": "cloud",
            "webServiceUrl": "https://pvt-pulsar-aws-useast2:8443",
            "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
            "websocketUrl": "",
            "pulsarInstance": "prod0",
            "regionZone": ""
        },
        "pulsar-aws-uswest2": {
            "clusterName": "pulsar-aws-uswest2",
            "cloudProvider": "aws",
            "cloudRegion": "uswest2",
            "clusterType": "cloud",
            "webServiceUrl": "https://pvt-pulsar-aws-uswest2:8443",
            "brokerServiceUrl": "pulsar+ssl://pulsar-aws-uswest2:6651",
            "websocketUrl": "",
            "pulsarInstance": "prod0",
            "regionZone": ""
        }
        ...TRUNCATED FOR READABILITY...
    }
}
----
====

=== Create geo-replication between namespaces

The JSON input parameters can be obtained from List Tenants with Details and Get a list cloud providers of {product} sections of this guide.

[source,curl]
----
curl --location --fail --request POST "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" --header "Content-Type: application/json" --header "Authorization: Bearer $ASTRA_TOKEN" --data-raw '{
  "bidirection": true,
  "destCluster": "pulsar-aws-uswest2",
  "email": "joshua@example.com",
  "namespace": "mynamespace",
  "originCluster": "pulsar-aws-useast2"
}'
----

No response indicates success.

=== Delete geo-replication between namespaces

The JSON input parameters can be obtained from List Tenants with Details and Get a list cloud providers of {product} sections of this guide.

[source,bash]
----
curl --location --fail --request DELETE "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" \
 --header "Content-Type: application/json" \
 --header "Authorization: Bearer $ASTRA_TOKEN" \
 --data-raw '{
  "bidirection": true,
  "destCluster": "pulsar-aws-uswest2",
  "email": "joshua@example.com",
  "namespace": "ns0",
  "originCluster": "pulsar-aws-useast2"
}'
----

No response indicates success.


== {product} {devops-api} {pulsar-short} token (JWT) operations

=== List existing token IDs

Get a list of Token IDs for your Cluster.
With the TokenID, you can then lookup and obtain the {pulsar-short} JWT string.
The TokenIDs are also listed in the {astra-ui} for that Tenant and Cluster.

Required parameters "CLUSTER" is obtained from the "List Tenants with Details" API command.

[source,curl]
----
curl --location --request GET "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens" --header "Authorization: Bearer $ASTRA_TOKEN" --header "X-DataStax-Pulsar-Cluster: $CLUSTER" | python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,console]
----
[
    {
        "iat": 1679335276,
        "iss": "datastax",
        "sub": "client;b282a256-b129-43e9-b870. . .",
        "tokenid": "cdb87797. . ."
    }
]
----
====

=== List token string by ID

[source,curl]
----
curl --fail --location --request GET "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens/$TOKENID" --header "X-DataStax-Pulsar-Cluster: $CLUSTER" --header "Authorization: Bearer $ASTRA_TOKEN"
----

.Result
[%collapsible]
====
[source,console]
----
Output: Raw string JWT
eyJhbGciOiJSUzI1NiIsI . . .
----
====

=== Create a JWT

Create a new {pulsar-short} JWT.
The new JWT will also be visible in the {astra-ui} for that Tenant and Cluster.

Required parameters "CLUSTER" is obtained from the "List Tenants with Details" API command.

[source,curl]
----
curl --fail --location --request POST "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens" --header "X-DataStax-Pulsar-Cluster: $CLUSTER" --header "Authorization: Bearer $ASTRA_TOKEN"
----

.Result
[%collapsible]
====
[source,console]
----
Output: new raw string JWT
eyJhbGciOiJSUzI1NiIsI . . .
----
====

=== Delete a JWT

Required parameters "CLUSTER" is obtained from the "List Tenants with Details" API command.
List of "TOKENID" can be obtained from List Existing Tokens IDs.

[source,curl]
----
curl --fail --location --request DELETE "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens" --header "X-DataStax-Pulsar-Cluster: $CLUSTER" --header "Authorization: Bearer $ASTRA_TOKEN"
----

No response indicates success.

== See also

* xref:apis:api-operations.adoc[]
* xref:developing:using-curl.adoc[]