= Use the {product} {devops-api}
:description: Learn about the {product} {devops-api}.

The {product} {devops-api} is one of the APIs that you can use to manage your {pulsar-reg} tenants and their resources.

Other available APIs include the xref:apis:api-operations.adoc[{product} {pulsar-short} Admin API], and the xref:

== {product} 

Use the xref:astra-streaming:apis:attachment$devops.html[{product} {devops-api}] to manage higher-level {product} objects associated with your {product-short} organization, such as the Change Data Capture (CDC) settings, {pulsar-short} tenants, geo-replications, {pulsar-short} stats, and {pulsar-short} tokens.

This API uses an {product-short} application token for authentication.

== {product} {pulsar-short} Admin API

Use the xref:astra-streaming:apis:attachment$pulsar-admin.html[{product} {pulsar-short} Admin API] to manage specific resources within a specific tenant, such as namespaces, topics, and subscriptions.

This API uses your {pulsar-short} token for authentication.

=== OSS {pulsar-short} Admin API

The https://pulsar.apache.org/admin-rest-api[open source {pulsar-short} project's {pulsar-short} Admin API] isn't the same as the {product} {pulsar-short} Admin API.

In OSS {pulsar-short} you manage instances, the clusters within each instance, the tenants in the cluster, and so on.
In {product}, clusters are a managed service.
You manage only the tenants and resources within those tenants.

Some OSS {pulsar-short} Admin API endpoints aren't supported in the {product} {pulsar-short} Admin API because they don't apply to the {product} managed service.

== See also

* xref:apis:api-operations.adoc[]
* xref:developing:using-curl.adoc[]