= Use the {product} {devops-api}
:description: Learn about the {product} {devops-api}.

The {product} {devops-api} is one of the APIs that you can use to manage your {pulsar-reg} tenants and their resources.
Use this API to manage higher-level {product} objects associated with your {product-short} organization, such as the Change Data Capture (CDC) settings, {pulsar-short} tenants, geo-replications, {pulsar-short} stats, and {pulsar-short} tokens.

This page summarizes commonly used endpoints.
For more information and all endpoints, see the xref:astra-streaming:apis:attachment$devops.html[{product} {devops-api} specification reference].

Other available APIs include the xref:apis:api-operations.adoc[{product} {pulsar-short} Admin API] and the xref:developing:using-curl.adoc[OSS {pulsar-reg} REST APIs].

== Prerequisites

To use the {product} {devops-api}, you need the following:

* An active {product-short} account with access to {product}.
* An xref:operations:astream-token-gen.adoc[{product-short} application token].
* Depending on the operations you need to perform, you might need additional information about your tenant.
You can get this information with `<<get-tenant-information,GET 'https://api.astra.datastax.com/v2/streaming/tenants'>>` or from the xref:operations:create-delete-tenants.adoc#get-tenant-information[**Tenant Details** section in the {astra-ui}].

=== Set environment variables

Due to their frequency in {product} {devops-api} calls, you might find it helpful to set the following environment variables:

[source,bash,subs="+quotes"]
----
export NAMESPACE="**NAMESPACE_NAME**"
export TENANT="**TENANT_NAME**"
export TOPIC="**TOPIC_NAME**"
export ASTRA_TOKEN="**ASTRA_APPLICATION_TOKEN**"
----

The examples in this guide use environment variables for these values.
For example:

//FIX the intro for all devops api code samples per below.
//Use double quotes around paths
[source,curl]
----
curl -sS -L -X GET "https://api.astra.datastax.com/v2/streaming/tenants" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
| python3 -mjson.tool
----

=== Format responses

include::ROOT:partial$format-api-response.adoc[]


//Bring devops api code samples from api-operations.adoc

== See also

* xref:apis:api-operations.adoc[]
* xref:developing:using-curl.adoc[]