= {product} APIs
:description: Learn about {product} APIs
:page-tag: astra-streaming,dev,develop,pulsar

You use two APIs to manage Pulsar tenants and their resources.

== {product} DevOps API

Use the xref:astra-streaming:apis:attachment$devops.html[{product} DevOps API] to manage higher level objects associated with your account, such as the change data capture (CDC) settings, Pulsar tenants, geo-replications, Pulsar stats, and Pulsar tokens.

This API uses an {astra_db} application token for authentication.

== {product} Pulsar Admin API

Use the xref:astra-streaming:apis:attachment$pulsar-admin.html[{product} Pulsar Admin API] to manage specific resources within a specific tenant, such as namespaces, topics, and subscriptions.

This API uses your Pulsar token for authentication.

=== OSS Pulsar Admin API

The https://pulsar.apache.org/admin-rest-api[open source Pulsar project's Pulsar Admin API] isn't the same as the {product} Pulsar Admin API.

In OSS Pulsar you manage instances, the clusters within each instance, the tenants in the cluster, and so on.
In {product}, clusters are a managed service.
You manage only the tenants and resources within those tenants.

Some OSS Pulsar Admin API endpoints aren't supported in the {product} Pulsar Admin API because they don't apply to the {product} managed service.

== See also

* xref:apis:api-operations.adoc[]
* xref:developing:using-curl.adoc[]
* https://pulsar.apache.org/docs/reference-rest-api-overview/[Pulsar REST APIs]