= Use the {product} {devops-api}
:description: Learn about the {product} {devops-api}.

The {product} {devops-api} is one of the APIs that you can use to manage your {pulsar-reg} tenants and their resources.
Use this API to manage higher-level {product} objects associated with your {product-short} organization, such as the Change Data Capture (CDC) settings, {pulsar-short} tenants, georeplication, {pulsar-short} stats, and {pulsar-short} tokens.

.More endpoints
[TIP]
====
This page summarizes commonly used endpoints.
For more information and all endpoints, see the xref:astra-streaming:apis:attachment$devops.html[{product} {devops-api} specification reference].
====

Other available APIs include the xref:apis:api-operations.adoc[{product} {pulsar-short} Admin API] and the xref:developing:using-curl.adoc[OSS {pulsar-reg} REST APIs].

[#prerequisites]
== Prerequisites

To use the {product} {devops-api}, you need the following:

* An active {product-short} account with access to {product}.

* An xref:operations:astream-token-gen.adoc[{product-short} application token] that has a role with {product} permissions.

* Depending on the operations you need to perform, you might need additional information about your tenant, such as the cluster name or {pulsar-short} instance name.
You can get this information with `<<get-tenant-details,GET "https://api.astra.datastax.com/v2/streaming/tenants">>` or from the xref:operations:create-delete-tenants.adoc#get-tenant-details[**Tenant Details** section in the {astra-ui}].

=== Set environment variables

Due to their frequency in {product} {devops-api} calls, you might find it helpful to set environment variables for the credentials and tenant details:

[source,bash,subs="+quotes"]
----
export INSTANCE="**PULSAR_INSTANCE_NAME**"
export TENANT="**TENANT_NAME**"
export NAMESPACE="**NAMESPACE_NAME**"
export TOPIC="**TOPIC_NAME**"
export ASTRA_TOKEN="**ASTRA_APPLICATION_TOKEN**"
----

To learn how to get these values, see <<prerequisites>>.

The examples in this guide use environment variables for these values.
For example, `--header "Authorization: Bearer $ASTRA_TOKEN"`.

=== Format responses

include::ROOT:partial$format-api-response.adoc[]

[#astra-streaming-devops-api-tenant-operations]
== Tenant operations

Use the following {product} {devops-api} endpoints to manage {product} {pulsar-short} tenants.

[#get-tenant-details]
=== Get tenant details

[source,curl]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/streaming/tenants" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
| python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,json]
----
[
  {
    "id": "14b77c47-bdfd-4ba1...",
    "tenantName": "mytenant",
    "clusterName": "pulsar-aws-useast2",
    "webServiceUrl": "https://pulsar-aws-useast2",
    "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
    "websocketUrl": "wss://pulsar-aws-useast2:8001/ws/v2",
    "websocketQueryParamUrl": "wss://pulsar-aws-useast2:8964/ws/v2",
    "pulsarToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpX...",
    "plan": "payg",
    "planCode": "1",
    "astraOrgGUID": "b282a256-b129-...",
    "cloudProvider": "aws",
    "cloudProviderCode": "1",
    "cloudRegion": "useast2",
    "status": "active",
    "jvmVersion": "JDK11",
    "pulsarVersion": "2.10.2",
    "regionZone": "na",
    "Email": "",
    "userMetricsUrl": "https://prometheus-aws-useast2...",
    "pulsarInstance": "prod0"
  },
  {
    "id": "e8bf25d8-a6a1-4169-...",
    "tenantName": "mytenant2",
    "clusterName": "pulsar-gcp-useast1",
    "webServiceUrl": "https://pulsar-gcp-useast1",
    "brokerServiceUrl": "pulsar+ssl://pulsar-gcp-useast1:6651",
    "websocketUrl": "wss://pulsar-gcp-useast1m:8001/ws/v2",
    "websocketQueryParamUrl": "wss://pulsar-gcp-useast1:8964/ws/v2",
    "pulsarToken": "eyJhbGciOiJSUz...",
    "plan": "payg",
    "planCode": "1",
    "astraOrgGUID": "b282a256-b129-43e9...",
    "cloudProvider": "gcp",
    "cloudProviderCode": "2",
    "cloudRegion": "useast1",
    "status": "active",
    "jvmVersion": "JDK11",
    "pulsarVersion": "2.10.2",
    "regionZone": "na",
    "Email": "",
    "userMetricsUrl": "https://prometheus-gcp-useast1...",
    "pulsarInstance": "prod0"
  }
]
----
====

[#get-cloud-providers-and-regions]
=== Get cloud providers and regions

Get cloud provider and regions supported by {product}:

[source,curl]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/streaming/providers" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
| python3 -mjson.tool
----

.Result
[%collapsible]
====
[source,json]
----
{
  "aws": [
    "useast1",
    "uswest2",
    "useast2"
  ],
  "azure": [
    "westus2",
    "eastus",
    "australiaeast"
  ],
  "gcp": [
    "useast1",
    "uscentral1",
    "australiase1",
    "europewest1",
    "useast4"
  ]
}
----
====

[#create-a-tenant]
=== Create a tenant

To create a tenant, you must provide the required tenant configuration settings in JSON format.
You can do this directly in the request body or with a JSON file.

* Create a tenant using in-line input:
+
[source,curl]
----
curl -sS --fail -L -X POST "https://api.astra.datastax.com/v2/streaming/tenants" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--data-raw '{
  "cloudProvider": "aws",
  "cloudRegion": "useast2",
  "tenantName": "mytenant",
  "userEmail": "joshua@example.com"
}' \
| python3 -mjson.tool
----

* Create a tenant using file input:
+
[source,curl]
----
curl -sS --fail -L -X POST "https://api.astra.datastax.com/v2/streaming/tenants" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--data "@mytenant-config.json" \
| python3 -mjson.tool
----
+
include::ROOT:partial$curl-file-input-tip.adoc[]

The output includes the new tenant's details and a `pulsarToken`, which is an initial xref:operations:astream-token-gen.adoc[{pulsar-short} JWT] for the new {pulsar-short} instance:

.Result
[source,json]
----
{
  "namespace": "default",
  "topic": "",
  "id": "",
  "tenantName": "mytenant",
  "clusterName": "pulsar-aws-useast2",
  "webServiceUrl": "https://pulsar-aws-useast2",
  "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
  "websocketUrl": "wss://pulsar-aws-useast2:8001/ws/v2",
  "websocketQueryParamUrl": "wss://pulsar-aws-useast2:8964/ws/v2",
  "pulsarToken": "eyJ...",
  "plan": "payg",
  "planCode": "",
  "astraOrgGUID": "b282a256-b129-43e9...",
  "cloudProvider": "aws",
  "cloudProviderCode": "",
  "cloudRegion": "useast2",
  "status": "active",
  "jvmVersion": "JDK11",
  "pulsarVersion": "2.10.2",
  "regionZone": "",
  "Email": "",
  "userMetricsUrl": "",
  "pulsarInstance": ""
}
----

[#delete-a-tenant]
=== Delete a tenant

[source,curl]
----
curl -sS --fail -L -X DELETE "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/clusters/$CLUSTER" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN"
----

== Georeplication operations

Use the following {product} {devops-api} endpoints to manage georeplication for {product} namespaces.
For more information, see xref:operations:astream-georeplication.adoc[].

=== Get georeplication settings

Get the georeplication settings for a namespace:

[source,curl]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
| python3 -mjson.tool
----

If georeplication is enabled, the response includes the replication configuration details.

.Result
[%collapsible]
====
[source,json]
----
{
  "pulsarInstance": "prod0",
  "tenant": "mytenant",
  "namespace": "mynamespace",
  "replications": {
    "pulsar-aws-useast2": [
      "pulsar-aws-uswest2",
      "pulsar-aws-useast2"
    ],
    "pulsar-aws-uswest2": [
      "pulsar-aws-uswest2",
      "pulsar-aws-useast2"
    ]
  },
  "clusters": {
    "pulsar-aws-useast2": {
      "clusterName": "pulsar-aws-useast2",
      "cloudProvider": "aws",
      "cloudRegion": "useast2",
      "clusterType": "cloud",
      "webServiceUrl": "https://pvt-pulsar-aws-useast2:8443",
      "brokerServiceUrl": "pulsar+ssl://pulsar-aws-useast2:6651",
      "websocketUrl": "",
      "pulsarInstance": "prod0",
      "regionZone": ""
    },
    "pulsar-aws-uswest2": {
      "clusterName": "pulsar-aws-uswest2",
      "cloudProvider": "aws",
      "cloudRegion": "uswest2",
      "clusterType": "cloud",
      "webServiceUrl": "https://pvt-pulsar-aws-uswest2:8443",
      "brokerServiceUrl": "pulsar+ssl://pulsar-aws-uswest2:6651",
      "websocketUrl": "",
      "pulsarInstance": "prod0",
      "regionZone": ""
    }
    ...TRUNCATED FOR READABILITY...
  }
}
----
====

=== Enable georeplication

To enable georeplication, provide the origin and destination clusters, the namespace, bidirectional flag, and the email address (if set for the tenant):

[source,curl]
----
curl -sS --fail -L -X POST "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--data-raw '{
  "bidirection": true,
  "destCluster": "pulsar-aws-uswest2",
  "email": "",
  "namespace": "ns0",
  "originCluster": "pulsar-aws-useast2"
}'
----

You can get the clusters, email, and namespace from <<get-tenant-details>>.

=== Disable (remove) georeplication

Specify the replication to remove by providing the entire georeplication settings object, including the origin and destination clusters, the namespace, bidirectional flag, and email address (if set for the tenant):

[source,curl]
----
curl -sS --fail -L -X DELETE "https://api.astra.datastax.com/v2/streaming/replications/$INSTANCE/$TENANT/$NAMESPACE" \
--header "Content-Type: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--data-raw '{
  "bidirection": true,
  "destCluster": "pulsar-aws-uswest2",
  "email": "",
  "namespace": "ns0",
  "originCluster": "pulsar-aws-useast2"
}'
----

You can get the clusters, email, and namespace from <<get-tenant-details>>.

== {pulsar-short} token (JWT) operations

Use the following {product} {devops-api} endpoints to manage {pulsar-short} tokens.
For more information, see xref:operations:astream-token-gen.adoc[].

[TIP]
====
For {product-short} application tokens, use the core xref:astra-db-serverless:api-reference:devops-api.adoc[{product-short} {devops-api}].
====

[#get-existing-pulsar-tokens]
=== Get existing {pulsar-short} tokens

Get a list of token IDs for a given tenant and cluster:

[source,curl]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--header "X-DataStax-Pulsar-Cluster: $CLUSTER" \
| python3 -mjson.tool
----

You can get the cluster name from <<get-tenant-details>>.

The result is a list of token objects, each containing the token ID and other metadata.
You can use the token ID to <<get-the-token-string-for-a-pulsar-token-id,get the corresponding {pulsar-short} token (JWT) string>>.

.Result
[source,json]
----
[
  {
    "iat": 1679335276,
    "iss": "datastax",
    "sub": "client;b282a256-b129-43e9-b870...",
    "tokenid": "cdb87797..."
  }
]
----

Token IDs are also listed in the {astra-ui} for each tenant and cluster.

[#get-the-token-string-for-a-pulsar-token-id]
=== Get the token string for a {pulsar-short} token ID

Get the raw string JWT associated with a specific token ID and cluster:

[source,curl,subs="+quotes"]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens/**PULSAR_TOKEN_ID**" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--header "X-DataStax-Pulsar-Cluster: $CLUSTER"
----

You can get token IDs from <<get-existing-pulsar-tokens>>, and you can get the cluster name from <<get-tenant-details>>.

.Result
[%collapsible]
====
[source,json]
----
Output: Raw string JWT
eyJhbGciOiJSUzI1NiIsI...
----
====

=== Create a {pulsar-short} token

Create a new {pulsar-short} token (JWT) for a given tenant and cluster.
You can get the cluster name from <<get-tenant-details>>.

[tabs]
======
v2 endpoint::
+
--
The `v2/streaming/tenants/$TENANT/tokens` endpoint returns a raw string JWT with an unlimited lifetime:

[source,curl]
----
curl -sS --fail -L -X POST "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--header "X-DataStax-Pulsar-Cluster: $CLUSTER"
----

.Result
[%collapsible]
====
[source,json]
----
Output: new raw string JWT
eyJhbGciOiJSUzI1NiIsI...
----
====
--

v3 endpoint::
+
--
The `v3/streaming/tenants/$TENANT/tokens` endpoint returns a JSON response and accepts additional token parameters:

[source,curl,subs="+quotes"]
----
curl -sS --fail -L -X POST "https://api.astra.datastax.com/v3/streaming/tenants/$TENANT/tokens" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--header "X-DataStax-Pulsar-Cluster: $CLUSTER" \
--data-raw '{
  "exp": "**EXPIRATION**",
  "role": "**ROLE**",
  "type": "**TYPE**"
}'
----

Replace the following:

* **`EXPIRATION`**: The token lifetime expressed as a number and unit, such as `1d` for one day.
* **`ROLE`**: A string describing the token's role.
* **`TYPE`**: The token's privilege level, either `admin` or `non-admin`.

.Result
[%collapsible]
====
[source,json]
----
{
  "id": "cdb87797...",
  "rolename": "admin",
  "token": "eyJhbGciOiJSUzI1NiIsI..."
}
----
====
--
======

=== Delete a {pulsar-short} token

Delete a token for a given cluster by token ID:

[source,curl,subs="+quotes"]
----
curl -sS --fail -L -X DELETE "https://api.astra.datastax.com/v2/streaming/tenants/$TENANT/tokens/**PULSAR_TOKEN_ID**" \
--header "Authorization: Bearer $ASTRA_TOKEN" \
--header "X-DataStax-Pulsar-Cluster: $CLUSTER"
----

You can get the token ID from <<get-existing-pulsar-tokens>>, and you can get the cluster name from <<get-tenant-details>>.

== See also

* xref:apis:api-operations.adoc[]
* xref:developing:using-curl.adoc[]