= Producing and consuming messages using the C# pulsar client on {product}
:navtitle: C#
:description: This is a guide to create a simple producer and consumer using Pulsar's C# client.

Go to the https://github.com/datastax/astra-streaming-examples[examples repo] for the complete source of this example.

== Prerequisites

* https://learn.microsoft.com/en-us/dotnet/core/install/[.NET 7 SDK]
* A Pulsar topic in {product}
* A text editor or IDE

== Create a console project

* Create a new console project, and then add a reference to the https://www.nuget.org/packages/DotPulsar/[dotpulsar client]:
+
[source,shell]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/create-project.sh[]
----

== Write the script

. In your new project, open the `Program.cs` file, and then remove any existing content from the file.

. Enter the following code, starting at line 1:
+
.Program.cs
[source,csharp]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/SimpleProducerConsumer/Program.cs[tag=build-client]
----
+
This code creates an instance of `PulsarClient`.
Notice that different configurations are chained together to choose how connections are handled.

. Provide values for the following variables:
+
include::developing:partial$client-variables-table.adoc[]

. Create a new `producer` instance, and then instruct it to produce a message in a string format.
Messages can also be in formats like JSON, byte, and AVRO.
+
.Program.cs
[source,csharp]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/SimpleProducerConsumer/Program.cs[tag=build-producer]
----

Asynchronously send a single message and wait for acknowledgment:
+
.Program.cs
[source,csharp]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/SimpleProducerConsumer/Program.cs[tag=produce-message]
----

. Create a new `consumer` instance and instruct it to expect messages in string format.
The consumer uses broker subscriptions to gather messages.
+
.Program.cs
[source,csharp]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/SimpleProducerConsumer/Program.cs[tag=build-consumer]
----
+
A subscription is set with a subscription name and an initial position.
In this example, the subscription starts with the `Earliest` unacknowledged message, which is also the first message in the topic.


. Loop through the messages provided to the consumer's subscription and write their contents:
+
.Program.cs
[source,csharp]
----
include::{astra-streaming-examples-repo}/csharp/simple-producer-consumer/SimpleProducerConsumer/Program.cs[tag=consumer-loop]
----

== Run the script

* In your project directory, run the script:
+
[source,shell]
----
dotnet run
----

Output such as the following indicates the script succeeded:

[source,console]
----
Sent message
Received: Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]