= Use the C# {pulsar-short} client on {product}
:navtitle: C#
:description: Produce and consume messages with the C# {pulsar-short} client and {product}.

You can produce and consume messages with the C# {pulsar-short} client and {product}.

For a complete source code example, see the https://github.com/datastax/astra-streaming-examples[{product} Examples repository].

== Prerequisites

* https://learn.microsoft.com/en-us/dotnet/core/install/[.NET 7 SDK]
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Create a console project

Create a new console project, and then add a reference to the https://www.nuget.org/packages/DotPulsar/[dotpulsar client]:

[source,shell]
----
dotnet new console \
  --output SimpleProducerConsumer \
  --framework net6.0

cd SimpleProducerConsumer

dotnet add package DotPulsar --version 2.7.0
----

== Write the script

. In your new project, open the `Program.cs` file, and then remove any existing content from the file.

. Enter the following code, starting at line 1:
+
.Program.cs
[source,csharp]
----
using DotPulsar;
using DotPulsar.Extensions;

var serviceUrl = "<REPLACE_WITH_SERVICE_URL>";
var pulsarToken = "<REPLACE_WITH_PULSAR_TOKEN>";

var tenantName = "<REPLACE_WITH_TENANT_NAME>";
var nmspace = "<REPLACE_WITH_NAMESPACE>";
var topicName = "<REPLACE_WITH_TOPIC>";

var topic = $"persistent://{tenantName}/{nmspace}/{topicName}";

await using var client = PulsarClient.Builder()
                                      .ServiceUrl(new Uri(serviceUrl))
                                      .Authentication(
                                        AuthenticationFactory.Token(pulsarToken)
                                      )
                                      .Build();
----
+
This code creates an instance of `PulsarClient`.
Notice that different configurations are chained together to choose how connections are handled.

. Provide values for the following variables:
+
include::ROOT:partial$client-variables-table.adoc[]

. Create a new `producer` instance, and then instruct it to produce a message in a string format.
Messages can also be in formats like JSON, byte, and AVRO.
+
.Program.cs
[source,csharp]
----
await using var producer = client.NewProducer(Schema.String)
                                 .Topic(topic)
                                 .Create();
----

. Asynchronously send a single message and wait for acknowledgment:
+
.Program.cs
[source,csharp]
----
await producer.Send("Hello World"); // Send a message and ignore the returned MessageId
Console.WriteLine("Sent message");
----

. Create a new `consumer` instance and instruct it to expect messages in string format.
The consumer uses broker subscriptions to gather messages.
+
.Program.cs
[source,csharp]
----
await using var consumer = client.NewConsumer(Schema.String)
                                 .SubscriptionName("examples-subscription")
                                 .Topic(topic)
                                 .InitialPosition(SubscriptionInitialPosition.Earliest)
                                 .Create();
----
+
A subscription is set with a subscription name and an initial position.
In this example, the subscription starts with the `Earliest` unacknowledged message, which is also the first message in the topic.

. Loop through the messages provided to the consumer's subscription and write their contents:
+
.Program.cs
[source,csharp]
----
var msgCount = 0;
await foreach (var message in consumer.Messages())
{
	msgCount++;
	Console.WriteLine($"Received: {message.Value()}");
	await consumer.Acknowledge(message);

	if(msgCount > 0) break;
}
----

== Run the script

In your project directory, run the script:

[source,shell]
----
dotnet run
----

Output such as the following indicates the script succeeded:

[source,console]
----
Sent message
Received: Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]