= Use the Golang {pulsar-short} client with {product}
:navtitle: Golang
:description: Produce and consume messages with the Golang {pulsar-short} client and {product}.
:page-tag: astra-streaming,dev,develop,pulsar,go

You can produce and consume messages with the Golang {pulsar-short} client and {product}.

For a complete source code example, see the https://github.com/datastax/astra-streaming-examples[{product} Examples repository].

== Prerequisites

* Golang version 1.15 or later
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Create a project

. Run the following script to create a project folder, change directory into it, and then initialize a new Go project:
+
[source,shell]
----
sudo apt install -y golang-go
mkdir SimpleProducerConsumer && cd SimpleProducerConsumer

go mod init SimpleProducerConsumer

touch main.go

go get -u github.com/apache/pulsar-client-go
----
+
The new project includes a `main` file and the retrieved {pulsar-short} client package.

== Write the script

. Open the `main.go` file, and then add the following code to import the required packages, establish an entry point for the application, and create a new instance of a {pulsar-short} client:
+
.main.go
[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-client]
----
+
This code is incomplete.
Your editor might show errors until you complete the next steps.

. Provide values for the following variables:
+
include::developing:partial$client-variables-table.adoc[]

. Use the client to create a producer.
+
.main.go
[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-producer]
----
+
While the client contains directions for where to connect and how to authenticate, the producer has the full topic address where a message is published.
The full topic address includes the tenant, namespace, and topic names, as well as topic persistence.

. Create a `Hello World` message and send it asynchronously:
+
.main.go
[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=produce-message]
----

. Use the client to create a new xref:ROOT:astream-subscriptions.adoc[subscription instance] to receive the message:
+
.main.go
[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-consumer]
----
+
A topic is set with a subscription name and an initial position.
In this example, the subscription starts with the `Earliest` unacknowledged message, which is also the first message in the topic.

. Make the consumer receive and acknowledge (`ack`) messages provided to the subscription:
+
.main.go
[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=receive-message]
----

== Run the script

In your project directory, run your Go app:

[source,shell]
----
go run main.go
----

Output such as the following indicates the script succeeded:

[source,console]
----
2023/01/04 13:43:00 Pulsar Producer
2023/01/04 13:43:00 creating producer...
2023/01/04 13:43:01 checking error of producer creation...
2023/01/04 13:43:01 the Hello World successfully published with the message ID 421788:1:0
2023/01/04 13:43:01 Received message : Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]