= Producing and consuming messages using the Golang pulsar client on {product}
:navtitle: Golang
:description: This is a guide to create a simple producer and consumer using Pulsar's golang client.
:page-tag: astra-streaming,dev,develop,pulsar,go

== Prerequisites

You will need the following prerequisites in place to complete this guide:

* Golang version 1.15 and above
* A working Pulsar topic (get started xref:getting-started:index.adoc[here] if you don't have a topic)
* A basic text editor or IDE

[TIP]
====
Visit our https://github.com/datastax/astra-streaming-examples[examples repo] to see the complete source of this example.
====

== Create a project

Create a new GO project.

Open a new terminal and run the following script to create a project folder, change directory into it, and initialize a new GO project.

[source,shell]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/create-project.sh[]
----

Within the new project, a "main" file is created and the Pulsar client package is retrieved.

== Add the client

Open the new "main.go" file in your editor and paste the following code within.

[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-client]
----

This is NOT a complete code snippet: it imports the required packages, establishes an entry point for the application, and creates a new instance of a Pulsar client.

Notice there are a few variables that are waiting for replacement values.
You can find those values here:

include::developing:partial$client-variables-table.adoc[]

== Create a producer

Use the client to create a producer.

While the client contains directions for where to connect and how to authenticate, the producer has the full topic address where a message will be published.
The full topic address includes the tenant, namespace, and topic names, as well as topic persistence.

Paste the following code in "main.go".

[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-producer]
----

Next step is to create a message to be sent. In our case we'll set the payload to something super memorable - "Hello World". And with a producer and message ready to go, we can asynchronously send.

Paste the following code in "main.go".

[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=produce-message]
----

== Create a consumer

What's a message for if it never gets read, right? Let's create a new subscription instance from the client.

Subscriptions are covered in more depth in xref:ROOT:astream-subscriptions.adoc[their own topic]{emoji-smile}, but for now, think of a consumer and a subscription as the same idea.

A topic is set with a subscription name and an initial position.
In this case our subscription will start with the "Earliest" unacknowledged message, which happens to be the first message in the topic.

Add the following code to your "main.go" file.

[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=build-consumer]
----

Add this code to your file to have the consumer receive and then acknowledge (or "ack") messages provided to the subscription.

[source,golang]
----
include::{astra-streaming-examples-repo}/go/simple-producer-consumer/SimpleProducerConsumer/main.go[tag=receive-message]
----

== Run the example

Your example GO application is complete. Here it is, your big moment!

Return to the terminal in the same folder as the "main.go" file, and run the application.

[source,shell]
----
go run main.go
----

If everything works as planned, you should see output similar to the following.

[source,shell]
----
2023/01/04 13:43:00 Pulsar Producer
2023/01/04 13:43:00 creating producer...
2023/01/04 13:43:01 checking error of producer creation...
2023/01/04 13:43:01 the Hello World successfully published with the message ID 421788:1:0
2023/01/04 13:43:01 Received message : Hello World
----

== Next steps

Your messaging skills are progressing well! Let's continue learning.

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]