= Use the Java {pulsar-short} client with {product}
:navtitle: Java
:description: Produce and consume messages with the Java {pulsar-short} client and {product}.
:page-tag: astra-streaming,dev,develop,pulsar,java

You can produce and consume messages with the Java {pulsar-short} client and {product}.

For a complete source code example, see the https://github.com/datastax/astra-streaming-examples[{product} Examples repository].

== Prerequisites

For this example, you need the following:

* JRE 8
* https://maven.apache.org/install.html[Maven]
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Create a project

. Create a new Maven project:
+
[source,shell]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/create-project.sh[]
----

. Add the {pulsar-short} client dependency in `pom.xml`:
+
.pom.xml
[source,xml]
----
<dependency>
  <groupId>org.apache.pulsar</groupId>
  <artifactId>pulsar-client</artifactId>
  <version>2.10.2</version>
</dependency>
----


. For this example, add the following build target in `pom.xml`.
This example creates a single artifact.
+
.pom.xml
[source,xml]
----
<build>
  <plugins>
    <plugin>
      <artifactId>maven-assembly-plugin</artifactId>
      <configuration>
        <archive>
          <manifest>
            <mainClass>org.example.App</mainClass>
          </manifest>
        </archive>
        <descriptorRefs>
          <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
      </configuration>
    </plugin>
  </plugins>
</build>
----

. If necessary, specify the compiler versions in `pom.xml`:
+
.pom.xml
[source,xml]
----
<properties>
  <maven.compiler.source>11</maven.compiler.source>
  <maven.compiler.target>11</maven.compiler.target>
</properties>
----

== Write the script

. In your project, navigate to `src/main/java/org/example`, and then open `App.java`.

. Remove any existing content from the file, and then add the following code that imports dependencies, creates a client instance, and configures the instance to use your {product} tenant:
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=build-client]
----
+
This class is incomplete.
Your editor might show errors until you complete the next steps.

. Provide values for the following variables:
+
include::developing:partial$client-variables-table.adoc[]

. Use the client to create a producer.
The producer builds on the client configuration for directions about what topic to produce messages to.
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=build-producer]
----

. Asynchronously send a single message to the broker and wait for acknowledgment:
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=produce-message]
----

. Create a new consumer instance.
This code directs the consumer to watch a certain topic, identifies the subscription for watching topics, and begins the subscription.
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=build-consumer]
----
+
. Receive the messages added by the producer:
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=consumer-loop]
----

. Clean up and close the class:
+
.App.java
[source,java]
----
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=close-consumer]
include::{astra-streaming-examples-repo}/java/simple-producer-consumer/SimpleProducerConsumer/src/main/java/org/example/App.java[tag=close-client]
----

== Run the script

Build and run the app:

[source,shell]
----
mvn clean package assembly:single
java -jar target/SimpleProducerConsumer-1.0-SNAPSHOT-jar-with-dependencies.jar
----

`Message received` output indicates the script succeeded:

[source,console]
----
Message received: Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]