= Use the Node.js {pulsar-short} client with {product}
:navtitle: Node.js
:description: Produce and consume messages with the Node.js {pulsar-short} client and {product}.

You can produce and consume messages with the Node.js {pulsar-short} client and {product}.

For a complete source code example, see the {astra-streaming-examples-repo}[{product} Examples repository].

== Prerequisites

* `sudo` permission to install dependencies
* Node.js version 10 or later
* npm 6 or later
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Set up the environment

Install the {cpp} {pulsar-short} library dependency required by the Node.js {pulsar-short} client npm package.

{pulsar-short} Node client versions 1.8 and later don't require installation of the {cpp} {pulsar-short} library dependency.

.Ubuntu-based Debian
[source,shell]
----
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/DEB/apache-pulsar-client.deb
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/DEB/apache-pulsar-client-dev.deb

sudo apt install -y ./apache-pulsar-client.deb
sudo apt install -y ./apache-pulsar-client*.deb

sudo ldconfig
----

.Centos/RHEL-based rpm
[source,shell]
----
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/RPMS/apache-pulsar-client-2.10.2-1.x86_64.rpm
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/RPMS/apache-pulsar-client-devel-2.10.2-1.x86_64.rpm

sudo rpm -i ./apache-pulsar-client-2.10.2-1.x86_64.rpm
sudo rpm -i ./apache-pulsar-client-devel-2.10.2-1.x86_64.rpm

sudo ldconfig
----

== Create a project

In a terminal, run the following script to create a new Node.js project.
If NPM asks for project values, use the automatically suggested defaults.

[source,shell]
----
mkdir SimpleProducerConsumer && cd SimpleProducerConsumer

touch index.js

npm init -y

npm install pulsar-client
----

== Write the script

. In your new project, open the `index.js` file, and then add the following code.
+
.index.js
[source,javascript]
----
const Pulsar = require("pulsar-client");

(async () => {
  const serviceUrl = "<REPLACE_WITH_SERVICE_URL>";
  const pulsarToken = "<REPLACE_WITH_PULSAR_TOKEN>";

  const tenantName = "<REPLACE_WITH_TENANT_NAME>";
  const namespace = "<REPLACE_WITH_NAMESPACE>";
  const topicName = "<REPLACE_WITH_TOPIC>";

  const topic = `persistent://${tenantName}/${namespace}/${topicName}`;

  // Debian Ubuntu:
  const trustStore = '/etc/ssl/certs/ca-certificates.crt'
  // CentOS RHEL:
  // const trustStore = "/etc/ssl/certs/ca-bundle.crt";

  const auth = new Pulsar.AuthenticationToken({ token: pulsarToken });

  const client = new Pulsar.Client({
    serviceUrl: serviceUrl,
    authentication: auth,
    tlsTrustCertsFilePath: trustStore,
    operationTimeoutSeconds: 30,
  });
----
+
This script is intentionally incomplete.
Your IDE might show errors until you complete the next steps.

. Provide values for the following variables:
+
include::ROOT:partial$client-variables-table.adoc[]

. Use the client to create a producer.
+
There are many configuration options for producers.
For this example, declare the topic where messages should go.
+
.index.js
[source,javascript]
----
  const producer = await client.createProducer({
    topic: topic,
  });
----

. Send a message and receive acknowledgment:
+
.index.js
[source,javascript]
----
  producer.send({
    data: Buffer.from("Hello World"),
  });
  console.log("sent message");
----

. Clean up:
+
.index.js
[source,javascript]
----
  await producer.flush();
  await producer.close();
----
+
At this point, the script produces a message that waits to be consumed and acknowledged.

. Create a new consumer subscription, name the subscription, and declare the topic to watch:
+
.index.js
[source,javascript]
----
  const consumer = await client.subscribe({
    topic: topic,
    subscription: "examples-subscription",
    subscriptionType: "Exclusive",
    ackTimeoutMs: 10000,
  });
----

. Receive messages, write them to the console, and acknowledge receipt with the broker:
+
.index.js
[source,javascript]
----
  const msg = await consumer.receive();
  console.log(msg.getData().toString());
  consumer.acknowledge(msg);
----

. Clean up:
+
.index.js
[source,javascript]
----
  await consumer.close();
  await client.close();
})();
----

== Run the script

In your Node.js project, run the script:

[source,shell]
----
node index.js
----

Output such as the following confirms that the script succeeded:

[source,console]
----
sent message
Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:connectors:index.adoc[]