= Use the Node.js {pulsar-short} client with {product}
:navtitle: Node.js
:description: Produce and consume messages with the Node.js {pulsar-short} client and {product}.
:page-tag: astra-streaming,connect,dev,develop,nodejs,pulsar

You can produce and consume messages with the Node.js {pulsar-short} client and {product}.

For a complete source code example, see the https://github.com/datastax/astra-streaming-examples[{product} Examples repository].

== Prerequisites

* `sudo` permission to install dependencies
* Node.js version 10 or later
* npm 6 or later
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Set up the environment

Install the {cpp} {pulsar-short} library dependency required by the Node.js {pulsar-short} client npm package.

{pulsar-short} Node client versions 1.8 and later do not require installation of the {cpp} {pulsar-short} library dependency.

[tabs]
======
Ubuntu-based Debian::
+
--
[source,shell]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/create-project.sh[tag=prep-env]
----
--

Centos/RHEL-based rpm::
+
--
[source,shell]
----
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/RPMS/apache-pulsar-client-2.10.2-1.x86_64.rpm
wget https://archive.apache.org/dist/pulsar/pulsar-2.10.2/RPMS/apache-pulsar-client-devel-2.10.2-1.x86_64.rpm

sudo rpm -i ./apache-pulsar-client-2.10.2-1.x86_64.rpm
sudo rpm -i ./apache-pulsar-client-devel-2.10.2-1.x86_64.rpm

sudo ldconfig
----
--
======

== Create a project

In a terminal, run the following script to create a new Node.js project.
If NPM asks for project values, use the automatically suggested defaults.

[source,shell]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/create-project.sh[tag=create-project]
----

== Write the script

. In your new project, open the `index.js` file, and then add the following code.
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=create-client]
----
+
This script is intentionally incomplete.
Your IDE might show errors until you complete the next steps.

. Provide values for the following variables:
+
include::developing:partial$client-variables-table.adoc[]

. Use the client to create a producer.
+
There are many configuration options for producers.
For this example, declare the topic where messages should go.
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=create-producer]
----

. Send a message and receive acknowledgment:
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=produce-message]
----

. Clean up:
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=cleanup-producer]
----
+
At this point, the script produces a message that waits to be consumed and acknowledged.

. Create a new consumer subscription, name the subscription, and declare the topic to watch:
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=create-consumer]
----

. Receive messages, write them to the console, and acknowledge receipt with the broker:
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=consume-message]
----

. Clean up:
+
.index.js
[source,javascript]
----
include::{astra-streaming-examples-repo}/nodejs/simple-producer-consumer/SimpleProducerConsumer/index.js[tag=cleanup-consumer]
----

== Run the script

In your Node.js project, run the script:

[source,shell]
----
node index.js
----

Output such as the following confirms that the script succeeded:

[source,console]
----
sent message
Hello World
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]