= Use the Python {pulsar-short} client with {product}
:navtitle: Python
:description: Use the Python {pulsar-short} client with {product} to produce and consume messages.
:page-tag: astra-streaming,dev,develop,python,pulsar

You can use the Python {pulsar-short} client with {product} to produce and consume messages.

Go to the https://github.com/datastax/astra-streaming-examples[examples repo] for the complete source of this example.

== Prerequisites

* A supported Python version:
** For Linux, versions 3.4 to 3.7 are supported
** For macOS, version 3.7 is supported
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Create a project

. Create a folder for a new Python project.

. In your new directory, install the {pulsar-short} client library with pip:
+
[source,shell]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/create-project.sh[]
----

== Write the script

. Create an `index.py` file containing the following code.
This code creates a {pulsar-short} client instance with the topic URL and token authentication.
+
.index.py
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-client]
----
+
This script is intentionally incomplete.
Your IDE might show errors until you complete the next steps.

. Provide values for the following variables:
+
include::developing:partial$client-variables-table.adoc[]

. Use the client to create a producer:
+
.index.py
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-producer]
----

. Send a message:
+
.index.py
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=produce-message]
----

. Use the Python client instance to create a consumer subscription to the same topic that you sent a message to:
+
.index.py
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-consumer]
----

. Iterate through messages and write their data:
+
.index.py
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=consume-message]
----

. Clean up:
+
[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=clean-up]
----

== Run the script

In your Python project directory, run the script:

[source,shell]
----
python3 index.py
----

The output includes a lot of logs.
`Received message` confirms that the script succeeded:

[source,console]
----
Received message 'Hello World' id='(422529,5,-1,0)'
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]