= Producing and consuming messages using the python pulsar client on Astra Streaming
:description: This is a guide to create a simple producer and consumer using Pulsar's python client.
:title: Python pulsar client on Astra Streaming
:page-aliases: docs@astra-streaming::astream-python-eg.adoc,astra-streaming:ROOT:astream-python-eg.adoc
:page-tag: astra-streaming,dev,develop,python,pulsar

== Prerequisites

You will need the following prerequisites in place to complete this guide:

* Linux Python versions 3.4 to 3.7 are supported
* MacOS version 3.7 is supported
* A working Pulsar topic (get started xref:getting-started:index.adoc[here] if you don't have a topic)
* A basic text editor or IDE

[TIP]
====
Visit our https://github.com/datastax/astra-streaming-examples/tree/master/astra-streaming-csharp-examples[examples repo^]{external-link-icon} to see the complete source of this example.
====

== Create a project

First things first let's create a folder, change in to it, and start a new python project.

[source,shell]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/create-project.sh[]
----

== Add the client

Open "index.py" in your favorite text editor or IDE and copy the following code in. This sets up the topic URL and creates a new pulsar client instance, using token authentication.

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-client]
----

Don't be alarmed if you see error messages in your editor, this is not complete code... yet. Notice there are a few variables waiting for a replacement value. Go ahead and fill those in.

include::partial$client-variables-table.adoc[]

== Create a producer

Now bring in the following code to "index.py" to use the client to create a message producer.

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-producer]
----

Send that message! (copy the following code in  to index.py)

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=produce-message]
----

== Create a consumer

Just like the producer, we'll use the client instance to create a consumer subscription to the same topic we sent a message to.

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=create-consumer]
----

And now for the good stuff! Let's iterate through messages and write their data.

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=consume-message]
----

Then a little clean-up.

[source,python]
----
include::{astra-streaming-examples-repo}/python/simple-producer-consumer/SimpleProducerConsumer/index.py[tag=clean-up]
----

== Run the example

Here it comes! Your greatest python creation ever. Run the following command in the terminal where you created the python project.

[source,python]
----
python3 index.py
----

There will probably be a lot of logging in the output but the following message is what you want to see.

[source,shell]
----
Received message 'Hello World' id='(422529,5,-1,0)'
----

== Next steps

You are one step closer to being a messaging ninja. Let's continue the learning with these guides.

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:streaming-learning:pulsar-io:connectors/index.adoc[]