= Use the Python {pulsar-short} client with {product}
:navtitle: Python
:description: Use the Python {pulsar-short} client with {product} to produce and consume messages.

This example demonstrates how you can use the Python {pulsar-short} client with {product} to produce and consume messages.

== Prerequisites

* A supported Python version:
** For Linux, versions 3.4 to 3.7 are supported
** For macOS, version 3.7 is supported
* An {pulsar-reg} topic in {product}
* A text editor or IDE

== Create a project

Create a directory for your Python project, create an `index.py` file, and then install the {pulsar-short} client library with pip:

[source,shell]
----
mkdir SimpleProducerConsumer && cd SimpleProducerConsumer

touch index.py

pip install pulsar-client==2.10
----

== Write the script

In the following steps you will add code to `index.py` to create a complete script that produces and consumes messages with the Python {pulsar-short} client and {product}.
Your IDE might show errors until you have completed the script.

. Open `index.py` in a text editor or IDE.

. Import the required libraries, and then create a {pulsar-short} client instance with the topic URL and token authentication:
+
.index.py
[source,python]
----
import pulsar
import time

serviceUrl = "<REPLACE_WITH_SERVICE_URL>";
pulsarToken = "<REPLACE_WITH_PULSAR_TOKEN>";

tenantName = "<REPLACE_WITH_TENANT_NAME>";
namespace = "<REPLACE_WITH_NAMESPACE>";
topicName = "<REPLACE_WITH_TOPIC>";

topic = "persistent://{0}/{1}/{2}".format(tenantName, namespace, topicName)

client = pulsar.Client(serviceUrl, authentication=pulsar.AuthenticationToken(pulsarToken))
----

. Provide values for the following variables:
+
include::ROOT:partial$client-variables-table.adoc[]

. Use the client to create a producer:
+
.index.py
[source,python]
----
producer = client.create_producer(topic)
----

. Send a message:
+
.index.py
[source,python]
----
producer.send('Hello World'.encode('utf-8'))
----

. Use the Python client instance to create a consumer subscription to the same topic that you sent a message to:
+
.index.py
[source,python]
----
consumer = client.subscribe(topic, 'my-subscription')
----

. Iterate through messages and write their data:
+
.index.py
[source,python]
----
waitingForMsg = True
while waitingForMsg:
    try:
        msg = consumer.receive(2000)
        print("Received message '{}' id='{}'".format(msg.data(), msg.message_id()))

        # Acknowledging the message to remove from message backlog
        consumer.acknowledge(msg)

        waitingForMsg = False
    except:
        print("Still waiting for a message...");

    time.sleep(1)
----

. Clean up:
+
[source,python]
----
client.close()
----

The complete `index.py` script is as follows:

.index.py
[source,python]
----
import pulsar
import time

serviceUrl = "<REPLACE_WITH_SERVICE_URL>";
pulsarToken = "<REPLACE_WITH_PULSAR_TOKEN>";

tenantName = "<REPLACE_WITH_TENANT_NAME>";
namespace = "<REPLACE_WITH_NAMESPACE>";
topicName = "<REPLACE_WITH_TOPIC>";

topic = "persistent://{0}/{1}/{2}".format(tenantName, namespace, topicName)

client = pulsar.Client(serviceUrl, authentication=pulsar.AuthenticationToken(pulsarToken))

producer = client.create_producer(topic)

producer.send('Hello World'.encode('utf-8'))

consumer = client.subscribe(topic, 'my-subscription')

waitingForMsg = True
while waitingForMsg:
    try:
        msg = consumer.receive(2000)
        print("Received message '{}' id='{}'".format(msg.data(), msg.message_id()))

        # Acknowledging the message to remove from message backlog
        consumer.acknowledge(msg)

        waitingForMsg = False
    except:
        print("Still waiting for a message...");

    time.sleep(1)

client.close()
----

== Run the script

In your Python project directory, run the script:

[source,shell]
----
python3 index.py
----

The output includes a lot of logs.
`Received message` confirms that the script succeeded:

[source,console]
----
Received message 'Hello World' id='(422529,5,-1,0)'
----

== Next steps

* xref:developing:configure-pulsar-env.adoc[]
* xref:developing:astream-functions.adoc[]
* xref:connectors:index.adoc[]