= {pulsar-short} I/O connectors in {product}
:navtitle: {pulsar-short} I/O connectors reference

{product} offers fully-managed versions of https://pulsar.apache.org/docs/en/io-overview/[{pulsar-reg} sink and source connectors].

[IMPORTANT]
====
{product} doesn't support custom sink or source connectors.
====

//Luna Streaming: Cloud Storage sink, Google BigQuery sink are experimental
//Elasticsearch is lowercase
//Luna Streaming extra Experimental source: Netty
//Luna Streaming -2.x and -1.x have fewer connectors

[#sink-connectors]
== Sink connectors

Sink connectors export messages from {pulsar-short} topics to external services.

Supported sink connectors::
The following sink connectors are included in {product}:
+
* xref:connectors/sinks/astra-db.adoc[{astra-db} and {cass} sink]
* xref:connectors/sinks/kafka.adoc[Apache Kafka sink]
* xref:connectors/sinks/kinesis.adoc[AWS Kinesis sink]
* xref:connectors/sinks/cloud-storage.adoc[Cloud Storage sink]
* xref:connectors/sinks/elastic-search.adoc[Elasticsearch sink]
* xref:connectors/sinks/google-bigquery.adoc[Google BigQuery sink]
* xref:connectors/sinks/jdbc-clickhouse.adoc[JDBC ClickHouse sink]
* xref:connectors/sinks/jdbc-mariadb.adoc[JDBC MariaDB sink]
* xref:connectors/sinks/jdbc-postgres.adoc[JDBC PostgreSQL sink]
* xref:connectors/sinks/jdbc-sqllite.adoc[JDBC SQLite sink]
* xref:connectors/sinks/snowflake.adoc[Snowflake sink]

Experimental sink connectors::
The following sink connectors are experimental.
They are in development, and they aren't fully supported or tested with {product}.
To get access to experimental connectors, contact {support-url}[{company} Support].
+
* Aerospike
* Apache Geode
* Apache HBase
* Apache Kudu
* Apache Phoenix
* Apache Solr
* Batch Data Generator
* CoAP
* Couchbase
* DataDog
* Diffusion
* Flume
* Hazelcast
* HDFS 2
* HDFS 3
* Humio
* InfluxDB
* JMS
* Kinetica
* MarkLogic
* Microsoft Azure Data Explorer (Kusto)
* Microsoft Azure DocumentDB
* MongoDB
* MQTT
* Neo4J
* New Relic
* OrientDB
* PLC4X
* RabbitMQ
* Redis
* SAP HANA
* SingleStore
* Splunk
* XTDB
* Zeebe

[#source-connectors]
== Source connectors

Source connectors ingest messages from external services into {pulsar-short} topics.

Supported source connectors::
The following source connectors are included in {product}:
+
* xref:connectors/sources/kafka.adoc[Apache Kafka source]
* xref:connectors/sources/kinesis.adoc[AWS Kinesis source]
* xref:connectors/sources/data-generator.adoc[Data Generator source]
* xref:connectors/sources/debezium-mongodb.adoc[Debezium MongoDB source]
* xref:connectors/sources/debezium-mysql.adoc[Debezium MySQL source]
* xref:connectors/sources/debezium-oracle.adoc[Debezium Oracle source]
* xref:connectors/sources/debezium-postgres.adoc[Debezium PostgreSQL source]
* xref:connectors/sources/debezium-sqlserver.adoc[Debezium SQL Server source]

Experimental source connectors::
The following source connectors are experimental.
They are in development, and they aren't fully supported or tested with {product}.
To get access to experimental connectors, contact {support-url}[{company} Support].
+
* {cass}
* Apache Geode
* Apache Kudu
* Apache Phoenix
* Batch Data Generator
* Big Query
* Canal
* CoAP
* Couchbase
* DataDog
* Diffusion
* DynamoDB
* File
* Flume
* Hazelcast
* Humio
* JMS
* Kinetica
* MarkLogic
* Microsoft Azure DocumentDB
* MongoDB
* MQTT
* Neo4J
* New Relic
* NSQ
* OrientDB
* PLC4X
* RabbitMQ
* Redis
* SAP HANA
* SingleStore
* Splunk
* Twitter
* XTDB
* Zeebe

== Create and manage connectors

You can use the {astra-ui}, the `xref:developing:produce-consume-pulsar-client.adoc[pulsar-admin]` CLI, or the xref:apis:api-operations.adoc[{pulsar-short} Admin API] to create, monitor, and manage sink and source connectors.

//Combine below sections w/ "use the Pulsar CLI" page (separate pulsar-client and pulsar-admin) and Admin API ref pages; then replace below w/ links to specific sections

=== Get available sink connectors

Get a list of sink connectors that are available in your {product} {pulsar-short} tenant:

.pulsar-admin CLI
[source,shell,subs="attributes+"]
----
./bin/pulsar-admin sinks available-sinks
----

.{pulsar-short} Admin API
[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sinks/builtinsinks" -H "Authorization: $PULSAR_TOKEN"
----

=== Get available source connectors

Get a list of source connectors that are available in your {product} {pulsar-short} tenant:

.pulsar-admin CLI
[source,shell,subs="attributes+"]
----
./bin/pulsar-admin sources available-sources
----

.{pulsar-short} Admin API
[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sources/builtinsources" -H "Authorization: $PULSAR_TOKEN"
----

=== Create or update a connector

Although you use the same base commands to create and update all {product} {pulsar-short} connectors, each connector has different configuration options.
For example commands and configuration details, see the documentation for your preferred <<sink-connectors,sink connectors>> and <<source-connectors,source connectors>>.

[#get-sink-connector-configuration-data]
=== Get sink connector configuration data

Get the configuration for an existing sink connector:

.pulsar-admin CLI
[source,shell]
----
# Get information about a connector
./bin/pulsar-admin sinks get \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Get information about a connector
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#get-source-connector-configuration-data]
=== Get source connector configuration data

Get the configuration for an existing source connector:

.pulsar-admin CLI
[source,shell]
----
# Get information about connector
./bin/pulsar-admin sources get \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Get a connector's information
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#start-a-sink-connector]
=== Start a sink connector

.pulsar-admin CLI
[source,shell]
----
# Start all instances of a connector
./bin/pulsar-admin sinks start \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only start an individual instance
----

.{pulsar-short} Admin API
[source,shell,subs="attributes+"]
----
# Start all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/start" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Start an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/$SINK_INSTANCE_ID/start" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#start-a-source-connector]
=== Start a source connector

.pulsar-admin CLI
[source,shell]
----
# Start all instances of a connector
./bin/pulsar-admin sources start \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only start an individual instance
----

.{pulsar-short} Admin API
[source,shell]
----
# Start all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/start" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Start an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/$SOURCE_INSTANCE_ID/start" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#stop-a-sink-connector]
=== Stop a sink connector

.pulsar-admin CLI
[source,shell]
----
# Stop all instances of a connector
./bin/pulsar-admin sinks stop \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only stop an individual instance
----

.{pulsar-short} Admin API
[source,shell]
----
# Stop all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/stop" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Stop an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/$SINK_INSTANCE_ID/stop" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#stop-a-source-connector]
=== Stop a source connector

.pulsar-admin CLI
[source,shell]
----
# Stop all instances of a connector
./bin/pulsar-admin sources stop \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only stop an individual instance
----

.{pulsar-short} Admin API
[source,shell]
----
# Stop all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/stop" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Stop an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/$SOURCE_INSTANCE_ID/stop" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#restart-a-sink-connector]
=== Restart a sink connector

.pulsar-admin CLI
[source,shell]
----
# Restart all instances of a connector
./bin/pulsar-admin sinks restart \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only restart an individual instance
----

.{pulsar-short} Admin API
[source,shell]
----
# Restart all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/restart" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Restart an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/$SINK_INSTANCE_ID/restart" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#restart-a-source-connector]
=== Restart a source connector

.pulsar-admin CLI
[source,shell]
----
# Restart all instances of a connector
./bin/pulsar-admin sources restart \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"

# optionally add --instance-id to only restart an individual instance
----

.{pulsar-short} Admin API
[source,shell]
----
# Restart all instances of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/restart" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Restart an individual instance of a connector
curl -sS --fail -L -X POST "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/$SOURCE_INSTANCE_ID/restart" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#get-sink-connector-status]
=== Get sink connector status

.pulsar-admin CLI
[source,shell]
----
# Check connector status
./bin/pulsar-admin sinks status \
  --instance-id "$SINK_INSTANCE_ID" \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Get the status of all connector instances
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/status" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Get the status of an individual connector instance
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME/$SINK_INSTANCE_ID/status" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

Status response for all connector instances:

.Result
[source,json]
----
{
 "numInstances": 0,
 "numRunning": 0,
 "instances": [
   {
     "instanceId": 0,
     "status": {
       "running": true,
       "error": "string",
       "numRestarts": 0,
       "numReadFromPulsar": 0,
       "numSystemExceptions": 0,
       "latestSystemExceptions": [
         {
           "exceptionString": "string",
           "timestampMs": 0
         }
       ],
       "numSinkExceptions": 0,
       "latestSinkExceptions": [
         {
           "exceptionString": "string",
           "timestampMs": 0
         }
       ],
       "numWrittenToSink": 0,
       "lastReceivedTime": 0,
       "workerId": "string"
     }
   }
 ]
}
----

Status response for individual connector instance:

.Result
[source,json]
----
{
 "running": true,
 "error": "string",
 "numRestarts": 0,
 "numReadFromPulsar": 0,
 "numSystemExceptions": 0,
 "latestSystemExceptions": [
   {
     "exceptionString": "string",
     "timestampMs": 0
   }
 ],
 "numSinkExceptions": 0,
 "latestSinkExceptions": [
   {
     "exceptionString": "string",
     "timestampMs": 0
   }
 ],
 "numWrittenToSink": 0,
 "lastReceivedTime": 0,
 "workerId": "string"
}
----

[#get-source-connector-status]
=== Get source connector status

.pulsar-admin CLI
[source,shell]
----
# Check connector status
./bin/pulsar-admin sources status \
  --instance-id "$SOURCE_INSTANCE_ID" \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Get the status of all connector instances
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/status" \
  --header "Authorization: Bearer $PULSAR_TOKEN"

# Get the status of an individual connector instance
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME/$SOURCE_INSTANCE_ID/status" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

Status response for all connector instances:

.Result
[source,json]
----
{
  "numInstances": 0,
  "numRunning": 0,
  "instances": [
    {
      "instanceId": 0,
      "status": {
        "running": true,
        "error": "string",
        "numRestarts": 0,
        "numReceivedFromSource": 0,
        "numSystemExceptions": 0,
        "latestSystemExceptions": [
          {
            "exceptionString": "string",
            "timestampMs": 0
          }
        ],
        "numSourceExceptions": 0,
        "latestSourceExceptions": [
          {
            "exceptionString": "string",
            "timestampMs": 0
          }
        ],
        "numWritten": 0,
        "lastReceivedTime": 0,
        "workerId": "string"
      }
    }
  ]
}
----

Status response for individual connector instance:

.Result
[source,json]
----
{
  "running": true,
  "error": "string",
  "numRestarts": 0,
  "numReceivedFromSource": 0,
  "numSystemExceptions": 0,
  "latestSystemExceptions": [
    {
      "exceptionString": "string",
      "timestampMs": 0
    }
  ],
  "numSourceExceptions": 0,
  "latestSourceExceptions": [
    {
      "exceptionString": "string",
      "timestampMs": 0
    }
  ],
  "numWritten": 0,
  "lastReceivedTime": 0,
  "workerId": "string"
}
----

[#delete-a-sink-connector]
=== Delete a sink connector

.pulsar-admin CLI
[source,shell]
----
# Delete all instances of a connector
./bin/pulsar-admin sinks delete \
  --namespace "$NAMESPACE" \
  --name "$SINK_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Delete all instances of a connector
curl -sS --fail -L -X DELETE "$WEB_SERVICE_URL/admin/v3/sinks/$TENANT/$NAMESPACE/$SINK_NAME" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

[#delete-a-source-connector]
=== Delete a source connector

.pulsar-admin CLI
[source,shell]
----
# Delete all instances of a connector
./bin/pulsar-admin sources delete \
  --namespace "$NAMESPACE" \
  --name "$SOURCE_NAME" \
  --tenant "$TENANT"
----

.{pulsar-short} Admin API
[source,shell]
----
# Delete all instances of a connector
curl -sS --fail -L -X DELETE "$WEB_SERVICE_URL/admin/v3/sources/$TENANT/$NAMESPACE/$SOURCE_NAME" \
  --header "Authorization: Bearer $PULSAR_TOKEN"
----

== Connector metrics

{product} exposes Prometheus-formatted metrics for every connector.
For more information, see xref:operations:astream-scrape-metrics.adoc[].