= Manage tokens

{product} uses two types of tokens that you can generate in {product-short}.

[#astra-token]
== {product-short} application tokens

{product-short} application tokens are access tokens for authentication to the {astra-ui} and the xref:apis:index.adoc[{product} {devops-api}].
You use these tokens for tenant administration, such as creating tenants and {pulsar-short} tokens (JWT)

To create an {product-short} application token, see xref:astra-db-serverless:administration:manage-application-tokens.adoc[].

[#pulsar-token]
== {product} {pulsar-short} tokens (JWT)

{product} {pulsar-short} tokens are {pulsar-reg} https://jwt.io/introduction/[JSON Web Token (JWT)] for authentication to your {product} {pulsar-short} cluster through the {pulsar-short} CLI, runtime clients, or the {pulsar-short} Admin API.
If necessary, {product-short} forwards the JWT to the {pulsar-short} cluster for role verification.

You need a {pulsar-short} JWT for actions related to {pulsar-short} tenants, namespaces, messages, topics, and functions, as well as {pulsar-short} CLI/API commands.

You can generate, copy, or delete {product} {pulsar-short} tokens for each of your {product} tenants:

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant where you want to manage tokens.

. Click the *Settings* tab.

. In the *Token Management* section, click *Create Token*.

. Select a token expiration from 7 days to never.
+
Practice responsible credential management:
+
* Be aware of the security implications for tokens that never expire.
* Consider how long you actually plan to use the token.

. Copy the token and store it securely.
+
The token is shown only once.

. To delete a token, click *Delete*.
+
Ensure you update your application with a new, valid {pulsar-short} token before deletion.
Applications using the deleted {pulsar-short} token will no longer be able to connect to {product}.

== Set environment variables

Consider setting environment variables for sensitive and frequently used values, such as your authentication credentials and xref:operations:create-delete-tenants.adoc#get-tenant-details[tenant connection details]:

[source,bash,subs="+quotes"]
----
export TENANT=**ASTRA_STREAMING_TENANT_NAME**
export WEB_SERVICE_URL=**ASTRA_STREAMING_TENANT_WEB_SERVICE_URL**
export PULSAR_TOKEN=**ASTRA_STREAMING_TENANT_PULSAR_TOKEN**
export ASTRA_TOKEN=**ASTRA_APPLICATION_TOKEN**
----

== When to use the tokens

The required credentials and connection details depend on the tool you use to interact with {product}:

{product} {devops-api}::
To send requests to the xref:apis:index.adoc[{product} {devops-api}], use an {product-short} application token.
+
For the {devops-api}, the base URL is always `\https://api.astra.datastax.com`.
+
For example:
+
.Billing report by tenant
[source,curl]
----
curl -sS --fail -L -X GET "https://api.astra.datastax.com/v2/stats/namespaces/$TENANT" \
--header "Accept: application/json" \
--header "Authorization: Bearer $ASTRA_TOKEN"
----

{product} {pulsar-short} Admin API::
To send requests to the xref:apis:api-operations.adoc[{product} {pulsar-short} Admin API], use your tenant's web service URL and a {pulsar-short} token.
For example:
+
.Get built-in sinks
[source,curl]
----
curl -sS --fail -L -X GET "$WEB_SERVICE_URL/admin/v3/sinks/builtinsinks" \
-H "Authorization: $ASTRA_PULSAR_TOKEN"
----

OSS {pulsar-short} REST APIs::
To send requests to the xref:developing:using-curl.adoc[open source {pulsar} project's REST APIs], use your tenant's web service URL and a {pulsar-short} token.

{pulsar-short} CLI::
Use a {pulsar-short} token to authenticate with the xref:developing:configure-pulsar-env.adoc[{pulsar-short} CLI].
+
The following commands use a {pulsar-short} token declared in the `pulsar-admin` binary configuration so the token doesn't have to be passed directly on the command line:
+
.Monitor a topic's health
[source,shell]
----
bin/pulsar-admin topics stats
----
+
.Monitor a connector's health
[source,shell]
----
bin/pulsar-admin sinks status
----

{astra-cli}::
Use an {product-short} application token to authenticate with the xref:developing:astra-cli.adoc[{astra-cli}].

== See also

* xref:astra-db-serverless:api-reference:devops-api.adoc[]
* xref:getting-started:index.adoc[]