= {product} regions
:description: {product} is available in specific AWS, Microsoft Azure, and Google Cloud regions.

{product} is available in a subset of the xref:astra-db-serverless:databases:regions.adoc[{astra-db} regions], including AWS, Microsoft Azure, and Google Cloud regions.

{product} tenants are regionally isolated.
The region you select when you create a tenant determines which databases that tenant can support.
For example, to enable xref:developing:astream-cdc.adoc[CDC for {astra-db}], your tenant must be in the same region as the relevant database.

Your ElasticSearch and Snowflake deployments can be in different regions than your {product} tenants.

If your preferred region isn't available, contact your {company} account representative or {support-url}[IBM Support].

[cols=3]
|===
|Cloud provider |Region |Location

|AWS
|`ap-south-1`
|Mumbai

|AWS
|`ap-southeast-1`
|Singapore

|AWS
|`ap-southeast-2`
|Sydney

|AWS
|`eu-central-1`
|Frankfurt

|AWS
|`eu-west-1`
|Ireland

|AWS
|`us-east-1`
|Virginia

|AWS
|`us-east-2`
|Ohio

|AWS
|`us-west-2`
|Oregon

|Google Cloud
|`australia-southeast1`
|Sydney

|Google Cloud
|`europe-west1`
|Belgium

|Google Cloud
|`europe-west3`
|Frankfurt

|Google Cloud
|`us-central1`
|Iowa

|Google Cloud
|`us-east1`
|South Carolina

|Google Cloud
|`us-east4`
|Virginia

|Azure
|`australiaeast`
|New South Wales

|Azure
|`eastus`
|Virginia

|Azure
|`westeurope`
|Netherlands

|Azure
|`westus2`
|Washington
|===