= {product} regions
:page-tag: astra-streaming,admin,manage,pulsar
:description: {product} is available in specific AWS, Microsoft Azure, and Google Cloud regions.

{product} is available in a subset of the xref:astra-db-serverless:databases:regions.adoc[{astra-db} regions], including AWS, Microsoft Azure, and Google Cloud regions.

{astra-stream} tenants are regionally isolated.
The region you select when you create a tenant determines which databases that tenant can support.
For example, to enable xref:developing:astream-cdc.adoc[CDC for {astra-db}], your tenant must be in the same region as the relevant database.

Your ElasticSearch and Snowflake deployments can be in different regions than your {product} tenants.

== AWS regions for {product}

[cols="1,1"]
|===
|Region |Location

|`ap-south-1`
|Mumbai

|`ap-southeast-1`
|Singapore

// |`ap-southeast-2`
// |Sydney

|`eu-central-1`
|Frankfurt

|`eu-west-1`
|Ireland

|`us-east-1`
|Virginia

|`us-east-2`
|Ohio

|`us-west-2`
|Oregon
|===

== Google Cloud regions for {product}

[cols="1,1"]
|===
|Region |Location

|`australia-southeast1`
|Sydney

|`europe-west1`
|Belgium

// |`europe-west3`
// |Frankfurt

|`us-central1`
|Iowa

|`us-east1`
|South Carolina

|`us-east4`
|Virginia

|===

== Microsoft Azure regions for {product}

[cols="1,1"]
|===
|Region |Location

|`australiaeast`
|New South Wales

|`eastus`
|Virginia

// |`eastus2`
// |Virginia

|`westeurope`
|Netherlands

|`westus2`
|Washington
|===

== Request a region

If your preferred region isn't available, contact your {company} account representative or {support_url}[{company} Support].