= Manage tokens

{product} uses two types of tokens that you can generate in {product-short}.

[#astra-token]
== Application tokens

{product-short} application tokens are access tokens for authentication to the {astra-ui} and the xref:apis:index.adoc[{devops-api}s].

To create an {product-short} application token, see xref:astra-db-serverless:administration:manage-application-tokens.adoc[].

[#pulsar-token]
== {product} {pulsar-short} tokens

{product} {pulsar-short} token are {pulsar-reg} https://jwt.io/introduction/[JSON Web Token (JWT)] for authentication to your {product} {pulsar-short} cluster through the {pulsar-short} CLI, runtime clients, or the {pulsar-short} Admin API.
If necessary, {product-short} forwards the JWT to the {pulsar-short} cluster for role verification.

You need a {pulsar-short} JWT for actions related to {pulsar-short} tenants, namespaces, messages, topics, and functions, as well as {pulsar-short} CLI/API commands.

You can generate, copy, or delete {product} {pulsar-short} tokens for each of your {product} tenants:

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. Click the name of your tenant where you want to manage tokens.

. Click the *Settings* tab.

. In the *Token Management* section, click *Create Token*.

. Select a token expiration from 7 days to never.
+
Practice responsible credential management:
+
* Be aware of the security implications for tokens that never expire.
* Consider how long you actually plan to use the token.

. Copy the token and store it securely.
+
The token is shown only once.

. To delete a token, click *Delete*.
+
Ensure you update your application with a new, valid {pulsar-short} token before deletion.
Applications using the deleted {pulsar-short} token will no longer be able to connect to {product}.

== Set environment variables

Create environment variables for your tenant's {pulsar-short} token and tenant web service URL:

. Create a <<pulsar-token,{pulsar-short} token>>.

. On your tenant's *Connect* tab, copy the *Web Service URL*.

. Set environment variables:
+
[source,shell,subs="attributes+"]
----
export WEB_SERVICE_URL=<replace-me>
export ASTRA_STREAMING_TOKEN=<replace-me>
----

. Use these values to form curl commands:
+
[source,shell,subs="attributes+"]
----
curl "$WEB_SERVICE_URL/admin/v3/sinks/builtinsinks" -H "Authorization: $ASTRA_STREAMING_TOKEN"
----

== Usage examples

The following examples show how you can use the two tokens for different actions.

=== Track monthly usage

Use an {product-short} application token to track monthly usage.
For example:

[source,curl,subs="+quotes"]
----
curl -sS --location -X GET "https://api.astra.datastax.com/v2/databases/**DATABASE_ID**" \
--header "Accept: application/json" \
--header "Authorization: Bearer **APPLICATION_TOKEN**"
----

=== Monitor a topic's health

Use a {pulsar-short} token to monitor a topic's health.
For example, the following command would authenticate through a {pulsar-short} token declared in the `pulsar-admin` binary configuration:

[source,shell]
----
bin/pulsar-admin topics stats
----

=== Monitor a connector's health

Use a {pulsar-short} token to monitor a connector's health.
For example:

[source,shell]
----
bin/pulsar-admin sinks status
----

=== Billing report by tenant

Use an {product-short} application token to get tenant billing reports.
For example:

[source,curl,subs="+quotes"]
----
curl -sS --location -X GET "https://api.astra.datastax.com/v2/stats/namespaces/**TENANT_NAME**" \
--header "Accept: application/json" \
--header "Authorization: Bearer **APPLICATION_TOKEN**"
----

== See also

* xref:getting-started:index.adoc[]