= {product_name} release notes
:slug: release-notes
:page-tag: astra-streaming,admin,dev,pulsar
:page-aliases: docs@astra-streaming::astream-release-notes.adoc

{product_name} release notes provide information about new and improved features, known and resolved issues, and bug fixes.

== 2 December 2022

{product_name} now supports https://pulsar.apache.org/docs/next/txn-how[Pulsar transactions].

== 21 November 2022

Added support for serverless Azure `australiaeast` (New South Wales, Australia) region. For more, see xref:operations:astream-regions.adoc[{product_name} regions].

== 11 November 2022

{product_name} now supports xref:streaming-learning:functions/index.adoc[transform functions].

== 16 September 2022

{product_name} now supports xref:operations:astream-georeplication.adoc[geo-replication].

== 7 June 2022

{product_name} now supports xref:operations:astream-scrape-metrics.adoc[scraping metrics with Prometheus].

== 28 April 2022

xref:developing:astream-rabbit.adoc[{starlight_rabbitmq}] is now available. {starlight_rabbitmq} brings native RabbitMQ® protocol support to Apache Pulsar™, enabling migration of existing RabbitMQ applications and services to Pulsar without modifying the code.

== 19 April 2022

xref:developing:astream-kafka.adoc[{kafka_for_astra}] is now available. {kafka_for_astra} brings native Apache Kafka(R) protocol support to Apache Pulsar.

== 24 March 2022 
xref:developing:astream-cdc.adoc[CDC for Astra DB] is now available. CDC for Astra DB automatically captures changes in real time, de-duplicates the changes, and streams the clean set of changed data into {product_name} where it can be processed by client applications or sent to downstream systems.

== 31 January 2022: General Availability
* Added support for serverless Google Cloud `us-central1` (Council Bluffs, Iowa) region. For more, see xref:operations:astream-regions.adoc[{product_name} regions].
* xref:operations:astream-token-gen.adoc[Pulsar tokens] simplify connecting to your streaming instances.
* Enabled xref:operations:astream-pricing.adoc[billing].

== 20 December 2021

Security upgrade to Log4J 2.17.0 to mitigate CVE-2021-45105.

== Public Preview

The Public Preview of {product_name} brings the ability to quickly create Apache Pulsar™ instances, manage your clusters, scale across cloud regions, and manage Pulsar resources such as topics, connectors, functions and subscriptions.

Instead of listing the features included in this release, learn about what {product_name} is, and then get started with data and event streaming.
If you have questions, review the xref:ROOT:astream-faq.adoc[FAQ] for answers.
