= {product} pricing
:page-tag: astra-streaming,planner,plan,pulsar

{product} is a fully-managed, software-as-a-service (SaaS) offering embedded in {product-short}.

There are three {product} subscription plans.
An {product} subscription is associated with an {product-short} organization, but {product} subscription plans are separate from {product-short} organization subscription plans.

For {product-short} plans and pricing details, see https://www.datastax.com/pricing?product=astra-db[{product-short} pricing] and xref:astra-db-serverless:administration:subscription-plans.adoc[].

== {product} subscription plans

The availability of {product} features depends on your {product} subscription plan.

The *Free* plan allows only one topic.
It is meant for evaluation before upgrading to a paid plan.

*Pay As You Go* and *Annual* plans can realize the benefits of fully-managed SaaS offerings.
You only pay for the resources you use to produce, process, and consume messages.
These plans require a payment method on file.
For {product} metering details, see https://www.datastax.com/pricing?product=astra-streaming[{product} pricing].

== Shared clusters

By default, {product} uses secure, shared {pulsar-reg} clusters.
Your data and interaction with {pulsar-short} are secured over a public internet connection.
If desired, you can opt in to <<dedicated-clusters,Streaming Capacity Units>>.

[#dedicated-clusters]
== Streaming Capacity Units

[TIP]
====
Streaming Capacity Units are also known as _dedicated clusters_.
====

If you prefer not to use shared clusters, you can opt for Streaming Capacity Units.

With Streaming Capacity Units, you have your own private {pulsar-short} cluster with all the benefits of {product} as a managed service.
You sign in to {product-short} and use {product} in the same way that you would on shared clusters.
When you create a tenant, you have the option to deploy to your private cluster.
This means that you can use both shared clusters and Streaming Capacity Units, depending on your tenants' use cases.

Streaming Capacity Units are an addition to your base {product} subscription plan, and billing for Streaming Capacity Units is unique to each customer.
For information about Streaming Capacity Unit pricing and metering, see https://www.datastax.com/astra-streaming-dedicated-clusters[{product-short} Streaming Capacity Units pricing].

Like shared clusters, all connections for Streaming Capacity Units in {product} are guarded by authentication, authorization, and secure (TLS) communications.
By default, these connections are over the public internet.
Additionally, Streaming Capacity Units support xref:operations:private-connectivity.adoc[private connectivity].

== Additional billed charges

Regardless of your subscription plan or cluster type, additional customizations can impact your {product} billed charges.
These include, but are not limited to, the following:

* Message retention duration
* Maximum message retention storage
* Number of tenants
* Region of tenant

== Limits

Regardless of your subscription plan or cluster type, {product} applies xref:astream-limits.adoc[guardrails and limits] on resource creation to ensure best practices, foster availability, and promote optimal configurations for your databases.

Streaming Capacity Units have fewer limits than shared clusters.

== Regions

With shared clusters, you can create tenants in any of the xref:astream-regions.adoc[supported regions].

Streaming Capacity Units are open to almost any public cloud region.
For this reason, Streaming Capacity Units offer more flexibility for xref:operations:astream-georeplication.adoc[geo-replication].
If your preferred region isn't already available, you can contact your {company} account representative or {support_url}[{company} Support] to request it.

== See also

* xref:ROOT:astream-faq.adoc[]
* xref:ROOT:astream-org-permissions.adoc[]
* xref:operations:monitoring/index.adoc#aggregate-astra-streaming-metrics[Aggregate {product} metrics]