= Manage Tokens

There are *two* different tokens within {astra_db} - the *{astra_db} application token* and the *{product} Pulsar token*.

The <<astra-token, {astra_db} token>> is used for authentication within {astra_ui} and the xref:apis:index.adoc[DevOps API].

The <<pulsar-token, Pulsar token>> is a native Pulsar JSON Web Token (JWT) token that controls authentication to the Pulsar cluster.

== What's the difference?

The {astra_db} token is an access token. It is used to authenticate your service account in the DevOps API and {astra_ui}.

The {product} Pulsar token is a JWT token. {astra_db} forwards the token on to the Pulsar cluster, which verifies if the role in allowed.

In general, actions related to your {astra_db} Org (tenant management, members, org billing, usage metrics, etc.) use your {astra_db} Token, and actions specific to a Pulsar tenant (message namespaces, topics, message metrics, etc.) use a Pulsar JWT token.

For more, see https://docs.datastax.com/en/streaming/astra-streaming/operations/onboarding-faq.html#secure-sign-on-roles-and-permissions[SSO Roles and Permissions].

[#astra-token]
== Generate {astra_db} token

The {astra_db} token can be generated in the <<DevOps API, DevOps API>> or the <<astra-token-ui, {astra_ui}>>.

=== DevOps API

. Create an application token to https://docs.datastax.com/en/astra/docs/_attachments/devopsv2.html[authenticate your service account] in the DevOps API.
. Once you have authenticated your service account, you can create and revoke tokens with the https://docs.datastax.com/en/astra/docs/_attachments/devopsv2.html[DevOps API].
. Get all clients within the organization:
+
[source,shell]
----
curl --request GET \
 --url 'https://api.astra.datastax.com/v2/clientIdSecrets' \
 --header 'Accept: application/json' \
 --header 'Authorization: Bearer <application_token>'
----
+
.Response
[%collapsible]
====
[source,json]
----
{"clients":[
	{"clientId":"DkFtHKMhDQDuQtlExkSzwbya",
		"roles":["21ef3576-0197-415a-b167-d510af12ecf0"],
		"generatedOn":"2021-02-22T17:09:58.668Z"},
	{"clientId":"eYSboCJaESiblJZnKZWMxROv",
		"roles":["21ef3576-0197-415a-b167-d510af12ecf0"],
		"generatedOn":"2021-04-28T18:49:11.323Z"}
]}
----
====

. Create an application token for a specific client:
+
[source,shell]
----
curl --request POST \
 --url 'https://api.astra.datastax.com/v2/clientIdSecrets' \
 --header 'Accept: application/json' \
 --header 'Authorization: Bearer <application_token>' \
 --data '{"roles": ["<roleId>"]}'
----
+
.Response
[%collapsible]
====
[source,json]
----
{
  "clientId":"zjCEYwRGWocLfQJHBNQxvorr",
  "secret":"SLR.cllL1Yz...",
  "orgId":"dccb8c32-cc2a-4bea-bd95-47ab8eb20510",
  "roles":["21ef3576-0197-415a-b167-d510af12ecf0"],
  "token":"AstraCS:...",
  "generatedOn":"2021-04-30T19:38:26.147847107Z"
}
----
====
+
[TIP]
====
For the `roleId`, provide the relevant role's `id` UUID value from a prior `GET` query, as shown in
https://docs.datastax.com/en/astra-serverless/docs/manage/devops/devops-roles.html#_creating_a_new_role[Getting existing roles in your organization].
The API results will show the UUID for each role id.
====

. In the command-line interface associated with your environment, paste the following environment variable copied from token generation:
+
[source,shell,subs="+quotes"]
----
export ASTRA_DB_APPLICATION_TOKEN=**APPLICATION_TOKEN**
----

[#astra-token-ui]
=== Generate an {astra_db} application token

. From any page in {astra_ui}, select the *Organizations* dropdown.

. In the main dropdown, select *Organization Settings*.

. From your Organization page, select *Token Management*.

. Select the role you want to attach to your token. The permissions for your selected role will be displayed.

. Select *Generate Token*. {product} will generate your token and display the _Client ID_, _Client Secret_, and _Token_.

. Download your _Client ID_, _Client Secret_, and _Token_.
+
[IMPORTANT]
====
After you navigate away from the page, you won't be able to download your _Client ID_, _Client Secret_, and _Token_ again.
====

. In the command-line interface associated with your environment, paste the following environment variable copied from token generation:
+
[source,shell,subs="+quotes"]
----
export ASTRA_DB_APPLICATION_TOKEN=**APPLICATION_TOKEN**
----

You can now execute DevOps API commands from your terminal to your database.

=== Delete {astra_db} token

If you need to limit access to your database, you can delete a token.

. Select the overflow menu for the token you want to delete.

. Select *Delete* to delete that token.

. If necessary, generate a new token for the same user role.

[#pulsar-token]
== Generate Pulsar token

To generate, copy, or delete {product} Pulsar tokens within your streaming tenant, visit the **Token Management** section of your streaming tenant's **Settings** page.
Select **Create Token** to generate a Pulsar token for this streaming tenant, and then copy the Pulsar token and store it securely.

Token duration ranges from 7 days to never expiring.
If you choose a token with an expiration, ensure you replace your token with a new, valid Pulsar token before the expiration date.

=== Set environment variables

Download your Pulsar connection info as detailed https://docs.datastax.com/en/astra-streaming/docs/astream-quick-start.html#download-connect-info[here].

In the command-line interface associated with your environment, paste the following environment variables copied for {product}:

[source,shell,subs="+quotes"]
----
export TENANT=**TENANT_NAME**
export INPUT_TOPIC=**INPUT_TOPIC_NAME**
export NAMESPACE=default
export BEARER_TOKEN=**PULSAR_TOKEN**
----

You can now execute Pulsar admin commands from your terminal to your database.

=== Delete Pulsar token

Select the **trashcan** icon to delete a Pulsar token.

Ensure you update your application with a new, valid Pulsar token before deletion. Applications using the deleted Pulsar token will no longer be able to connect to {product}.

For more on JSON Web Tokens, see the https://jwt.io/introduction/[JWT documentation].

== Which token should I use?

The line between {astra_db} and {product} tokens can be a little unclear.

Think of `pulsar-admin` and the DevOps API as complementary tools with different scopes.

Use `pulsar-admin` for interacting with your Pulsar clusters. Topics, namespaces, tenants, and their metrics fall under this scope.

Use the DevOps API for org-wide {astra_db} scope. Users, tenants, billing, and usage metrics fall under this scope.

Some cases can use `pulsar-admin` **or** the DevOps API - we want the tools to be complementary, not restrictive, so do what works best for you!

This section should help you choose which tool to use, and which token is required:

=== Track monthly usage

Use an {astra_db} application token to track monthly usage.
For example:

[source,shell]
----
curl --request GET \
--url 'https://api.astra.datastax.com/v2/databases/<DATABASE_ID>' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer <BEARER_TOKEN>'
----

=== Monitor a topic's health

Use a Pulsar token to monitor a topic's health.
For example:

[source,shell]
----
bin/pulsar-admin topics stats
----

=== Monitor a connector's health

Use a Pulsar token to monitor a connector's health.
For example:

[source,shell]
----
bin/pulsar-admin sinks status
----

=== Billing report by tenant

Use an {astra_db} application token to get tenant billing reports.
For example:

[source,shell]
----
curl --request GET \
--url https://api.astra.datastax.com/admin/v2/stats/namespaces/<tenant>
--header 'Accept: application/json' \
--header 'Authorization: Bearer <BEARER_TOKEN>'
----

== See also

* *xref:getting-started:index.adoc[]