= Private connectivity

[IMPORTANT]
====
Private links are available only for xref:operations:astream-pricing.adoc#dedicated-clusters[dedicated clusters].
====

To better protect your streaming connections, connect {product} to a private link service for <<inbound,inbound>> connectivity, or to a private endpoint for <<outbound,outbound>> connectivity.

Private connections are only available within the same cloud provider and region as your {product} cluster.

== Enable private links

To enable a private link service or private endpoint for {product}, contact {support_url}[{company} Support].
Be prepared to provide the <<credentials,credentials>> required for your cloud provider.

== Inbound traffic

{product} supports inbound traffic flowing from your private endpoint to {product}.

The first inbound traffic pattern describes Pulsar, Kafka, and RabbitMQ messaging traffic, as well as Prometheus metrics traffic, flowing from a user's private endpoint to {product}.

You create a connection to the {company} private link service, and then {company} routes traffic to your {product} dedicated cluster.
If you have multiple tenants, they can have different VPCs.
Each VPC will have the same private FQDN with different VNETs.
The traffic on separate private end point connections is isolated until it reaches the {company} load balancer.

The private link service pattern is the same across cloud providers, but the hostname depends on your cloud provider and region:

[#inbound]
.Inbound private link service endpoints
[cols="1,3"]
|===
|Service |Endpoint pattern

|Pulsar Messaging
|`pulsar-azure-eastus.private.streaming.datastax.com:6651`

|Kafka Messaging
|`kafka-azure-eastus.private.streaming.datastax.com:9093`

|RabbitMQ Messaging
|`rabbitmq-azure-eastus.private.streaming.datastax.com`

|Prometheus Metrics
|`prometheus-azure-eastus.private.streaming.datastax.com`
|===

[#outbound]
== Outbound traffic

On a case-by-case basis, {product} can support private outbound traffic flowing from {product} to your private endpoint.

The outbound traffic pattern creates a private endpoint in {product} that connects to your private link service.
{company} opens a port on the tenant's firewall to allow connectors and functions running in a dedicated namespace on a {product} cluster to connect to your private network.
Each tenant has its own firewall.

[#credentials]
== Cloud provider credentials

Each cloud provider requires specific credentials to connect to a private endpoint.
For information about private link configuration and credentials, see your cloud provider's documentation.

.Private link credentials and documentation
[cols="1,1,3"]
|===
|Cloud provider |Credentials required |Documentation

|AWS
|AWS account numbers
|https://docs.aws.amazon.com/vpc/latest/privatelink/endpoint-service.html[AWS Private Link]

|Microsoft Azure
|Azure subscription IDs
|https://learn.microsoft.com/en-us/azure/private-link/create-private-endpoint-portal?tabs=dynamic-ip[Azure Private Link]

|Google Cloud
|GCP project IDs
|https://console.cloud.google.com/net-services/psc/[Google Cloud Private Service Connect]
|===
