. Select the namespace and one or more input topics for the function.

. If needed, select an output namespace and topics.
+
Whether you need to specify an output topic depends on the function's logic.
For example, the `cast` xref:developing:astream-functions-transform.adoc[transform function] needs an output topic to receive the transformed messages.

. Optional: Select a log topic.
+
The log topic is a separate output topic for messages containing additional `loglevel`, `fqn`, and `instance` properties.

. Optional: Configure advanced settings:
+
* *Instances*: Enter a number of sink instances to run.
* *Processing Guarantee*: Select one of the following:
** *ATLEAST_ONCE* (default): Each message sent to the function can be processed one or more times.
** *ATMOST_ONCE*: Each message sent to the function is processed 0 or 1 times.
This means there is a change that a message is not processed.
** *EFFECTIVELY_ONCE*: Each message sent to the function has only one output associated with it.
* *Timeout*: Set a timeout limit.
* *Auto Acknowledge*: Enable or disable automatic message acknowledgment.

. If needed, provide a JSON-formatted config key for your function.
This configuration depends on your function code.

. Click *Create*.

. Confirm your function was created on the *Functions* tab.
+
You can also verify the function deployment with the {pulsar-short} CLI:
+
[source,shell]
----
./bin/pulsar-admin functions list --tenant $TENANT
----

Once created, the function starts processing messages from the input topics according to its logic.